//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.deleteBeneficiaryBankAccount;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v3.deleteBeneficiaryBankAccount package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeleteBeneficiaryBankAccount_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v3/services/deleteBeneficiaryBankAccount", "deleteBeneficiaryBankAccount");
    private final static QName _DeleteBeneficiaryBankAccountResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v3/services/deleteBeneficiaryBankAccount", "deleteBeneficiaryBankAccountResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v3.deleteBeneficiaryBankAccount
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteBeneficiaryBankAccountType }
     * 
     */
    public DeleteBeneficiaryBankAccountType createDeleteBeneficiaryBankAccountType() {
        return new DeleteBeneficiaryBankAccountType();
    }

    /**
     * Create an instance of {@link DeleteBeneficiaryBankAccountResponseType }
     * 
     */
    public DeleteBeneficiaryBankAccountResponseType createDeleteBeneficiaryBankAccountResponseType() {
        return new DeleteBeneficiaryBankAccountResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBeneficiaryBankAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v3/services/deleteBeneficiaryBankAccount", name = "deleteBeneficiaryBankAccount")
    public JAXBElement<DeleteBeneficiaryBankAccountType> createDeleteBeneficiaryBankAccount(DeleteBeneficiaryBankAccountType value) {
        return new JAXBElement<DeleteBeneficiaryBankAccountType>(_DeleteBeneficiaryBankAccount_QNAME, DeleteBeneficiaryBankAccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBeneficiaryBankAccountResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v3/services/deleteBeneficiaryBankAccount", name = "deleteBeneficiaryBankAccountResponse")
    public JAXBElement<DeleteBeneficiaryBankAccountResponseType> createDeleteBeneficiaryBankAccountResponse(DeleteBeneficiaryBankAccountResponseType value) {
        return new JAXBElement<DeleteBeneficiaryBankAccountResponseType>(_DeleteBeneficiaryBankAccountResponse_QNAME, DeleteBeneficiaryBankAccountResponseType.class, null, value);
    }

}
