//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.getBalance;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v2.getBalance package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBalanceResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v2/services/getBalance", "getBalanceResponse");
    private final static QName _GetBalance_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v2/services/getBalance", "getBalance");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v2.getBalance
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBalanceResponseType }
     * 
     */
    public GetBalanceResponseType createGetBalanceResponseType() {
        return new GetBalanceResponseType();
    }

    /**
     * Create an instance of {@link GetBalanceType }
     * 
     */
    public GetBalanceType createGetBalanceType() {
        return new GetBalanceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBalanceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v2/services/getBalance", name = "getBalanceResponse")
    public JAXBElement<GetBalanceResponseType> createGetBalanceResponse(GetBalanceResponseType value) {
        return new JAXBElement<GetBalanceResponseType>(_GetBalanceResponse_QNAME, GetBalanceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBalanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v2/services/getBalance", name = "getBalance")
    public JAXBElement<GetBalanceType> createGetBalance(GetBalanceType value) {
        return new JAXBElement<GetBalanceType>(_GetBalance_QNAME, GetBalanceType.class, null, value);
    }

}
