//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.getStatement;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v4.getStatement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetStatementResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v4/services/getStatement", "getStatementResponse");
    private final static QName _GetStatement_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v4/services/getStatement", "getStatement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v4.getStatement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStatementType }
     * 
     */
    public GetStatementType createGetStatementType() {
        return new GetStatementType();
    }

    /**
     * Create an instance of {@link GetStatementResponseType }
     * 
     */
    public GetStatementResponseType createGetStatementResponseType() {
        return new GetStatementResponseType();
    }

    /**
     * Create an instance of {@link StatementLineItemType }
     * 
     */
    public StatementLineItemType createStatementLineItemType() {
        return new StatementLineItemType();
    }

    /**
     * Create an instance of {@link StatementLineItemsListType }
     * 
     */
    public StatementLineItemsListType createStatementLineItemsListType() {
        return new StatementLineItemsListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatementResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v4/services/getStatement", name = "getStatementResponse")
    public JAXBElement<GetStatementResponseType> createGetStatementResponse(GetStatementResponseType value) {
        return new JAXBElement<GetStatementResponseType>(_GetStatementResponse_QNAME, GetStatementResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v4/services/getStatement", name = "getStatement")
    public JAXBElement<GetStatementType> createGetStatement(GetStatementType value) {
        return new JAXBElement<GetStatementType>(_GetStatement_QNAME, GetStatementType.class, null, value);
    }

}
