//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v5.payoutRequest;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v1.common.payoutbase.PayerType;
import com.earthport.bind.v1.common.payoutbase.PayoutDetailsType;
import com.earthport.bind.v1.common.payoutbase.ServiceLevelType;
import com.earthport.bind.v1.common.payoutbase.TransactionHoldType;
import com.earthport.bind.v2.common.core.MonetaryValueType;
import com.earthport.bind.v3.common.bankbase.UsersBankIDType;


/**
 * <p>Java class for PayoutRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayoutRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usersBankID" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}UsersBankIDType"/>
 *         &lt;element name="merchantTransactionReference" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantTransactionRefType"/>
 *         &lt;element name="payoutRequestAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="beneficiaryAmountInformation" type="{http://customer.endpoint.earthport.com/api/merchant/v5/services/payoutRequest}BeneficiaryAmountInformationType" minOccurs="0"/>
 *         &lt;element name="serviceLevel" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}ServiceLevelType" minOccurs="0"/>
 *         &lt;element name="beneficiaryStatementNarrative" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericDescriptionType" minOccurs="0"/>
 *         &lt;element name="fxTicketID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}UIDType" minOccurs="0"/>
 *         &lt;element name="requestedFXType" type="{http://customer.endpoint.earthport.com/api/merchant/v5/services/payoutRequest}RequestedFXType" minOccurs="0"/>
 *         &lt;element name="payerType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}PayerType" minOccurs="0"/>
 *         &lt;element name="payoutType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}PayoutType" minOccurs="0"/>
 *         &lt;element name="payoutDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}PayoutDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="transactionHold" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}TransactionHoldType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayoutRequestType", propOrder = {
    "usersBankID",
    "merchantTransactionReference",
    "payoutRequestAmount",
    "beneficiaryAmountInformation",
    "serviceLevel",
    "beneficiaryStatementNarrative",
    "fxTicketID",
    "requestedFXType",
    "payerType",
    "payoutType",
    "payoutDetails",
    "transactionHold"
})
public class PayoutRequestType {

    @XmlElement(required = true)
    protected UsersBankIDType usersBankID;
    @XmlElement(required = true)
    protected String merchantTransactionReference;
    protected MonetaryValueType payoutRequestAmount;
    protected BeneficiaryAmountInformationType beneficiaryAmountInformation;
    @XmlElement(defaultValue = "standard")
    protected ServiceLevelType serviceLevel;
    protected String beneficiaryStatementNarrative;
    @XmlElement(defaultValue = "0")
    protected Long fxTicketID;
    protected RequestedFXType requestedFXType;
    protected PayerType payerType;
    protected String payoutType;
    protected List<PayoutDetailsType> payoutDetails;
    protected TransactionHoldType transactionHold;
    @XmlAttribute(name = "version", required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the usersBankID property.
     * 
     * @return
     *     possible object is
     *     {@link UsersBankIDType }
     *     
     */
    public UsersBankIDType getUsersBankID() {
        return usersBankID;
    }

    /**
     * Sets the value of the usersBankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersBankIDType }
     *     
     */
    public void setUsersBankID(UsersBankIDType value) {
        this.usersBankID = value;
    }

    /**
     * Gets the value of the merchantTransactionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTransactionReference() {
        return merchantTransactionReference;
    }

    /**
     * Sets the value of the merchantTransactionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTransactionReference(String value) {
        this.merchantTransactionReference = value;
    }

    /**
     * Gets the value of the payoutRequestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getPayoutRequestAmount() {
        return payoutRequestAmount;
    }

    /**
     * Sets the value of the payoutRequestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setPayoutRequestAmount(MonetaryValueType value) {
        this.payoutRequestAmount = value;
    }

    /**
     * Gets the value of the beneficiaryAmountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryAmountInformationType }
     *     
     */
    public BeneficiaryAmountInformationType getBeneficiaryAmountInformation() {
        return beneficiaryAmountInformation;
    }

    /**
     * Sets the value of the beneficiaryAmountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryAmountInformationType }
     *     
     */
    public void setBeneficiaryAmountInformation(BeneficiaryAmountInformationType value) {
        this.beneficiaryAmountInformation = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceLevelType }
     *     
     */
    public ServiceLevelType getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceLevelType }
     *     
     */
    public void setServiceLevel(ServiceLevelType value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the beneficiaryStatementNarrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryStatementNarrative() {
        return beneficiaryStatementNarrative;
    }

    /**
     * Sets the value of the beneficiaryStatementNarrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryStatementNarrative(String value) {
        this.beneficiaryStatementNarrative = value;
    }

    /**
     * Gets the value of the fxTicketID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFxTicketID() {
        return fxTicketID;
    }

    /**
     * Sets the value of the fxTicketID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFxTicketID(Long value) {
        this.fxTicketID = value;
    }

    /**
     * Gets the value of the requestedFXType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedFXType }
     *     
     */
    public RequestedFXType getRequestedFXType() {
        return requestedFXType;
    }

    /**
     * Sets the value of the requestedFXType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedFXType }
     *     
     */
    public void setRequestedFXType(RequestedFXType value) {
        this.requestedFXType = value;
    }

    /**
     * Gets the value of the payerType property.
     * 
     * @return
     *     possible object is
     *     {@link PayerType }
     *     
     */
    public PayerType getPayerType() {
        return payerType;
    }

    /**
     * Sets the value of the payerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerType }
     *     
     */
    public void setPayerType(PayerType value) {
        this.payerType = value;
    }

    /**
     * Gets the value of the payoutType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayoutType() {
        return payoutType;
    }

    /**
     * Sets the value of the payoutType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayoutType(String value) {
        this.payoutType = value;
    }

    /**
     * Gets the value of the payoutDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payoutDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayoutDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayoutDetailsType }
     * 
     * 
     */
    public List<PayoutDetailsType> getPayoutDetails() {
        if (payoutDetails == null) {
            payoutDetails = new ArrayList<PayoutDetailsType>();
        }
        return this.payoutDetails;
    }

    /**
     * Gets the value of the transactionHold property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHoldType }
     *     
     */
    public TransactionHoldType getTransactionHold() {
        return transactionHold;
    }

    /**
     * Sets the value of the transactionHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHoldType }
     *     
     */
    public void setTransactionHold(TransactionHoldType value) {
        this.transactionHold = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
