//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.endpoint.customer.api.merchant.v1.processwalletpayment;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v1.common.payoutbase.PayerType;
import com.earthport.bind.v1.common.payoutbase.PayoutDetailsType;
import com.earthport.bind.v1.common.walletBaseTypes.WalletType;
import com.earthport.bind.v2.common.core.MonetaryValueType;
import com.earthport.bind.v2.common.identitybase.PayerIdentityType;


/**
 * <p>Java class for processWalletPaymentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processWalletPaymentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchantUserIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantUserIdentityType"/>
 *         &lt;element name="managedMerchantIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantIdentityType" minOccurs="0"/>
 *         &lt;element name="payerIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}PayerIdentityType" minOccurs="0"/>
 *         &lt;element name="merchantWalletID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}merchantWalletIDType" minOccurs="0"/>
 *         &lt;element name="wallet" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletType"/>
 *         &lt;element name="providerWalletDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v1/processWalletPayment}providerWalletDetailsType"/>
 *         &lt;element name="quoteId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="remittanceId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="merchantTransactionReference" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantTransactionRefType"/>
 *         &lt;element name="payoutRequestAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="beneficiaryAmountInformation" type="{http://customer.endpoint.earthport.com/api/merchant/v1/processWalletPayment}BeneficiaryAmountInformationType" minOccurs="0"/>
 *         &lt;element name="requestedFXType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/processWalletPayment}RequestedFXType" minOccurs="0"/>
 *         &lt;element name="beneficiaryStatementNarrative" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericDescriptionType" minOccurs="0"/>
 *         &lt;element name="fxTicketID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}UIDType" minOccurs="0"/>
 *         &lt;element name="payerType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}PayerType" minOccurs="0"/>
 *         &lt;element name="payoutDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}PayoutDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processWalletPaymentType", propOrder = {
    "merchantUserIdentity",
    "managedMerchantIdentity",
    "payerIdentity",
    "merchantWalletID",
    "wallet",
    "providerWalletDetails",
    "quoteId",
    "remittanceId",
    "merchantTransactionReference",
    "payoutRequestAmount",
    "beneficiaryAmountInformation",
    "requestedFXType",
    "beneficiaryStatementNarrative",
    "fxTicketID",
    "payerType",
    "payoutDetails"
})
public class ProcessWalletPaymentType {

    @XmlElement(required = true)
    protected String merchantUserIdentity;
    protected String managedMerchantIdentity;
    protected PayerIdentityType payerIdentity;
    protected String merchantWalletID;
    @XmlElement(required = true)
    protected WalletType wallet;
    @XmlElement(required = true)
    protected ProviderWalletDetailsType providerWalletDetails;
    protected long quoteId;
    protected long remittanceId;
    @XmlElement(required = true)
    protected String merchantTransactionReference;
    protected MonetaryValueType payoutRequestAmount;
    protected BeneficiaryAmountInformationType beneficiaryAmountInformation;
    protected RequestedFXType requestedFXType;
    protected String beneficiaryStatementNarrative;
    @XmlElement(defaultValue = "0")
    protected Long fxTicketID;
    protected PayerType payerType;
    protected List<PayoutDetailsType> payoutDetails;
    @XmlAttribute(name = "version", required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the merchantUserIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantUserIdentity() {
        return merchantUserIdentity;
    }

    /**
     * Sets the value of the merchantUserIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantUserIdentity(String value) {
        this.merchantUserIdentity = value;
    }

    /**
     * Gets the value of the managedMerchantIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagedMerchantIdentity() {
        return managedMerchantIdentity;
    }

    /**
     * Sets the value of the managedMerchantIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagedMerchantIdentity(String value) {
        this.managedMerchantIdentity = value;
    }

    /**
     * Gets the value of the payerIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIdentityType }
     *     
     */
    public PayerIdentityType getPayerIdentity() {
        return payerIdentity;
    }

    /**
     * Sets the value of the payerIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIdentityType }
     *     
     */
    public void setPayerIdentity(PayerIdentityType value) {
        this.payerIdentity = value;
    }

    /**
     * Gets the value of the merchantWalletID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantWalletID() {
        return merchantWalletID;
    }

    /**
     * Sets the value of the merchantWalletID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantWalletID(String value) {
        this.merchantWalletID = value;
    }

    /**
     * Gets the value of the wallet property.
     * 
     * @return
     *     possible object is
     *     {@link WalletType }
     *     
     */
    public WalletType getWallet() {
        return wallet;
    }

    /**
     * Sets the value of the wallet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletType }
     *     
     */
    public void setWallet(WalletType value) {
        this.wallet = value;
    }

    /**
     * Gets the value of the providerWalletDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderWalletDetailsType }
     *     
     */
    public ProviderWalletDetailsType getProviderWalletDetails() {
        return providerWalletDetails;
    }

    /**
     * Sets the value of the providerWalletDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderWalletDetailsType }
     *     
     */
    public void setProviderWalletDetails(ProviderWalletDetailsType value) {
        this.providerWalletDetails = value;
    }

    /**
     * Gets the value of the quoteId property.
     * 
     */
    public long getQuoteId() {
        return quoteId;
    }

    /**
     * Sets the value of the quoteId property.
     * 
     */
    public void setQuoteId(long value) {
        this.quoteId = value;
    }

    /**
     * Gets the value of the remittanceId property.
     * 
     */
    public long getRemittanceId() {
        return remittanceId;
    }

    /**
     * Sets the value of the remittanceId property.
     * 
     */
    public void setRemittanceId(long value) {
        this.remittanceId = value;
    }

    /**
     * Gets the value of the merchantTransactionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTransactionReference() {
        return merchantTransactionReference;
    }

    /**
     * Sets the value of the merchantTransactionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTransactionReference(String value) {
        this.merchantTransactionReference = value;
    }

    /**
     * Gets the value of the payoutRequestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getPayoutRequestAmount() {
        return payoutRequestAmount;
    }

    /**
     * Sets the value of the payoutRequestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setPayoutRequestAmount(MonetaryValueType value) {
        this.payoutRequestAmount = value;
    }

    /**
     * Gets the value of the beneficiaryAmountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryAmountInformationType }
     *     
     */
    public BeneficiaryAmountInformationType getBeneficiaryAmountInformation() {
        return beneficiaryAmountInformation;
    }

    /**
     * Sets the value of the beneficiaryAmountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryAmountInformationType }
     *     
     */
    public void setBeneficiaryAmountInformation(BeneficiaryAmountInformationType value) {
        this.beneficiaryAmountInformation = value;
    }

    /**
     * Gets the value of the requestedFXType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestedFXType }
     *     
     */
    public RequestedFXType getRequestedFXType() {
        return requestedFXType;
    }

    /**
     * Sets the value of the requestedFXType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestedFXType }
     *     
     */
    public void setRequestedFXType(RequestedFXType value) {
        this.requestedFXType = value;
    }

    /**
     * Gets the value of the beneficiaryStatementNarrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryStatementNarrative() {
        return beneficiaryStatementNarrative;
    }

    /**
     * Sets the value of the beneficiaryStatementNarrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryStatementNarrative(String value) {
        this.beneficiaryStatementNarrative = value;
    }

    /**
     * Gets the value of the fxTicketID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFxTicketID() {
        return fxTicketID;
    }

    /**
     * Sets the value of the fxTicketID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFxTicketID(Long value) {
        this.fxTicketID = value;
    }

    /**
     * Gets the value of the payerType property.
     * 
     * @return
     *     possible object is
     *     {@link PayerType }
     *     
     */
    public PayerType getPayerType() {
        return payerType;
    }

    /**
     * Sets the value of the payerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerType }
     *     
     */
    public void setPayerType(PayerType value) {
        this.payerType = value;
    }

    /**
     * Gets the value of the payoutDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payoutDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayoutDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayoutDetailsType }
     * 
     * 
     */
    public List<PayoutDetailsType> getPayoutDetails() {
        if (payoutDetails == null) {
            payoutDetails = new ArrayList<PayoutDetailsType>();
        }
        return this.payoutDetails;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
