//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.endpoint.customer.api.merchant.v3.notification;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.earthport.bind.v1.common.notificationbase.NotificationAcknowledgementType;
import com.earthport.bind.v1.common.notificationbase.NotificationType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.endpoint.customer.api.merchant.v3.notification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Notification_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v3/notification", "notification");
    private final static QName _NotificationAcknowledgement_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v3/notification", "notificationAcknowledgement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.endpoint.customer.api.merchant.v3.notification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v3/notification", name = "notification")
    public JAXBElement<NotificationType> createNotification(NotificationType value) {
        return new JAXBElement<NotificationType>(_Notification_QNAME, NotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationAcknowledgementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v3/notification", name = "notificationAcknowledgement")
    public JAXBElement<NotificationAcknowledgementType> createNotificationAcknowledgement(NotificationAcknowledgementType value) {
        return new JAXBElement<NotificationAcknowledgementType>(_NotificationAcknowledgement_QNAME, NotificationAcknowledgementType.class, null, value);
    }

}
