//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.common.financialtransaction;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinancialTransactionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FinancialTransactionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Payout"/>
 *     &lt;enumeration value="Refund"/>
 *     &lt;enumeration value="User Deposit"/>
 *     &lt;enumeration value="Merchant Liquidity Deposit"/>
 *     &lt;enumeration value="Journal"/>
 *     &lt;enumeration value="Merchant Liquidity Movement"/>
 *     &lt;enumeration value="Wallet Payment"/>
 *     &lt;enumeration value="Wallet Payment Refund"/>
 *     &lt;enumeration value="Earthport Merchant Liquidity Transfer"/>
 *     &lt;enumeration value="Transaction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FinancialTransactionTypeType")
@XmlEnum
public enum FinancialTransactionTypeType {

    @XmlEnumValue("Payout")
    PAYOUT("Payout"),
    @XmlEnumValue("Refund")
    REFUND("Refund"),
    @XmlEnumValue("User Deposit")
    USER_DEPOSIT("User Deposit"),
    @XmlEnumValue("Merchant Liquidity Deposit")
    MERCHANT_LIQUIDITY_DEPOSIT("Merchant Liquidity Deposit"),
    @XmlEnumValue("Journal")
    JOURNAL("Journal"),
    @XmlEnumValue("Merchant Liquidity Movement")
    MERCHANT_LIQUIDITY_MOVEMENT("Merchant Liquidity Movement"),
    @XmlEnumValue("Wallet Payment")
    WALLET_PAYMENT("Wallet Payment"),
    @XmlEnumValue("Wallet Payment Refund")
    WALLET_PAYMENT_REFUND("Wallet Payment Refund"),
    @XmlEnumValue("Earthport Merchant Liquidity Transfer")
    EARTHPORT_MERCHANT_LIQUIDITY_TRANSFER("Earthport Merchant Liquidity Transfer"),
    @XmlEnumValue("Transaction")
    TRANSACTION("Transaction");
    private final String value;

    FinancialTransactionTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FinancialTransactionTypeType fromValue(String v) {
        for (FinancialTransactionTypeType c: FinancialTransactionTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
