//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.common.financialtransaction;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v4.common.financialtransaction package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v4.common.financialtransaction
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WalletPaymentTransactionType }
     * 
     */
    public WalletPaymentTransactionType createWalletPaymentTransactionType() {
        return new WalletPaymentTransactionType();
    }

    /**
     * Create an instance of {@link WalletPaymentRejectTransactionType }
     * 
     */
    public WalletPaymentRejectTransactionType createWalletPaymentRejectTransactionType() {
        return new WalletPaymentRejectTransactionType();
    }

    /**
     * Create an instance of {@link PayoutTransactionDetailType }
     * 
     */
    public PayoutTransactionDetailType createPayoutTransactionDetailType() {
        return new PayoutTransactionDetailType();
    }

    /**
     * Create an instance of {@link GenericTransactionType }
     * 
     */
    public GenericTransactionType createGenericTransactionType() {
        return new GenericTransactionType();
    }

    /**
     * Create an instance of {@link FinancialTransactionsListType }
     * 
     */
    public FinancialTransactionsListType createFinancialTransactionsListType() {
        return new FinancialTransactionsListType();
    }

    /**
     * Create an instance of {@link RefundType }
     * 
     */
    public RefundType createRefundType() {
        return new RefundType();
    }

    /**
     * Create an instance of {@link FinancialTransactionStatusType }
     * 
     */
    public FinancialTransactionStatusType createFinancialTransactionStatusType() {
        return new FinancialTransactionStatusType();
    }

    /**
     * Create an instance of {@link StatementDetail.StatementDetailItem }
     * 
     */
    public StatementDetail.StatementDetailItem createStatementDetailStatementDetailItem() {
        return new StatementDetail.StatementDetailItem();
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link EarthportMerchantLiquidityTransferType }
     * 
     */
    public EarthportMerchantLiquidityTransferType createEarthportMerchantLiquidityTransferType() {
        return new EarthportMerchantLiquidityTransferType();
    }

    /**
     * Create an instance of {@link MerchantLiquidityMovementType }
     * 
     */
    public MerchantLiquidityMovementType createMerchantLiquidityMovementType() {
        return new MerchantLiquidityMovementType();
    }

    /**
     * Create an instance of {@link RefundDetailType }
     * 
     */
    public RefundDetailType createRefundDetailType() {
        return new RefundDetailType();
    }

    /**
     * Create an instance of {@link UserDepositType }
     * 
     */
    public UserDepositType createUserDepositType() {
        return new UserDepositType();
    }

    /**
     * Create an instance of {@link LiquidityDepositType }
     * 
     */
    public LiquidityDepositType createLiquidityDepositType() {
        return new LiquidityDepositType();
    }

    /**
     * Create an instance of {@link StatementDetail }
     * 
     */
    public StatementDetail createStatementDetail() {
        return new StatementDetail();
    }

    /**
     * Create an instance of {@link WalletPaymentRejectTransactionDetailType }
     * 
     */
    public WalletPaymentRejectTransactionDetailType createWalletPaymentRejectTransactionDetailType() {
        return new WalletPaymentRejectTransactionDetailType();
    }

    /**
     * Create an instance of {@link PayoutTransactionType }
     * 
     */
    public PayoutTransactionType createPayoutTransactionType() {
        return new PayoutTransactionType();
    }

    /**
     * Create an instance of {@link JournalDetailType }
     * 
     */
    public JournalDetailType createJournalDetailType() {
        return new JournalDetailType();
    }

    /**
     * Create an instance of {@link MerchantLiquidityMovementDetailType }
     * 
     */
    public MerchantLiquidityMovementDetailType createMerchantLiquidityMovementDetailType() {
        return new MerchantLiquidityMovementDetailType();
    }

    /**
     * Create an instance of {@link UserDepositDetailType }
     * 
     */
    public UserDepositDetailType createUserDepositDetailType() {
        return new UserDepositDetailType();
    }

    /**
     * Create an instance of {@link WalletPaymentTransactionDetailType }
     * 
     */
    public WalletPaymentTransactionDetailType createWalletPaymentTransactionDetailType() {
        return new WalletPaymentTransactionDetailType();
    }

    /**
     * Create an instance of {@link EarthportMerchantLiquidityTransferDetailType }
     * 
     */
    public EarthportMerchantLiquidityTransferDetailType createEarthportMerchantLiquidityTransferDetailType() {
        return new EarthportMerchantLiquidityTransferDetailType();
    }

    /**
     * Create an instance of {@link LiquidityDepositDetailType }
     * 
     */
    public LiquidityDepositDetailType createLiquidityDepositDetailType() {
        return new LiquidityDepositDetailType();
    }

}
