//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.common.financialtransaction;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Provides additional detail about a money movement.
 * 
 * <p>Java class for StatementDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatementDetailItem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="type" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="UniqueTransactionId"/>
 *                       &lt;enumeration value="InstructedCurrency"/>
 *                       &lt;enumeration value="InstructedAmount"/>
 *                       &lt;enumeration value="SettledCurrency"/>
 *                       &lt;enumeration value="SettledAmount"/>
 *                       &lt;enumeration value="SettledDate"/>
 *                       &lt;enumeration value="DebitCreditIndicator"/>
 *                       &lt;enumeration value="TransactionType"/>
 *                       &lt;enumeration value="TransactionNarrative"/>
 *                       &lt;enumeration value="AdditionalNarrative"/>
 *                       &lt;enumeration value="OriginatorBank"/>
 *                       &lt;enumeration value="OriginatorAccountNumber"/>
 *                       &lt;enumeration value="OriginatorNameAddressCombined"/>
 *                       &lt;enumeration value="OriginatorAccountName"/>
 *                       &lt;enumeration value="OriginatorAddress"/>
 *                       &lt;enumeration value="OriginatorCity"/>
 *                       &lt;enumeration value="OriginatorCountry"/>
 *                       &lt;enumeration value="OriginatorDOB"/>
 *                       &lt;enumeration value="OriginatorNationalId"/>
 *                       &lt;enumeration value="BeneficiaryNameAddressCombined"/>
 *                       &lt;enumeration value="BeneficiaryName"/>
 *                       &lt;enumeration value="BeneficiaryDOB"/>
 *                       &lt;enumeration value="BeneficiaryNationalId"/>
 *                       &lt;enumeration value="BeneficiaryAddress"/>
 *                       &lt;enumeration value="BeneficiaryCity"/>
 *                       &lt;enumeration value="BeneficiaryCountry"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementDetail", propOrder = {
    "statementDetailItem"
})
public class StatementDetail {

    @XmlElement(name = "StatementDetailItem")
    protected List<StatementDetail.StatementDetailItem> statementDetailItem;

    /**
     * Gets the value of the statementDetailItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statementDetailItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatementDetailItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatementDetail.StatementDetailItem }
     * 
     * 
     */
    public List<StatementDetail.StatementDetailItem> getStatementDetailItem() {
        if (statementDetailItem == null) {
            statementDetailItem = new ArrayList<StatementDetail.StatementDetailItem>();
        }
        return this.statementDetailItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="UniqueTransactionId"/>
     *             &lt;enumeration value="InstructedCurrency"/>
     *             &lt;enumeration value="InstructedAmount"/>
     *             &lt;enumeration value="SettledCurrency"/>
     *             &lt;enumeration value="SettledAmount"/>
     *             &lt;enumeration value="SettledDate"/>
     *             &lt;enumeration value="DebitCreditIndicator"/>
     *             &lt;enumeration value="TransactionType"/>
     *             &lt;enumeration value="TransactionNarrative"/>
     *             &lt;enumeration value="AdditionalNarrative"/>
     *             &lt;enumeration value="OriginatorBank"/>
     *             &lt;enumeration value="OriginatorAccountNumber"/>
     *             &lt;enumeration value="OriginatorNameAddressCombined"/>
     *             &lt;enumeration value="OriginatorAccountName"/>
     *             &lt;enumeration value="OriginatorAddress"/>
     *             &lt;enumeration value="OriginatorCity"/>
     *             &lt;enumeration value="OriginatorCountry"/>
     *             &lt;enumeration value="OriginatorDOB"/>
     *             &lt;enumeration value="OriginatorNationalId"/>
     *             &lt;enumeration value="BeneficiaryNameAddressCombined"/>
     *             &lt;enumeration value="BeneficiaryName"/>
     *             &lt;enumeration value="BeneficiaryDOB"/>
     *             &lt;enumeration value="BeneficiaryNationalId"/>
     *             &lt;enumeration value="BeneficiaryAddress"/>
     *             &lt;enumeration value="BeneficiaryCity"/>
     *             &lt;enumeration value="BeneficiaryCountry"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StatementDetailItem {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
