//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.common.financialtransaction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.earthport.bind.v2.common.core.FXExecutedRateType;
import com.earthport.bind.v2.common.core.MonetaryValueType;


/**
 * 
 * 				A financial transaction representing money paid into a merchant's account by a user.
 * 				This element contains all details pertaining to this financial transaction.
 * 			
 * 
 * <p>Java class for UserDepositDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDepositDetailType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v4/components/financialTransactionBase}UserDepositType">
 *       &lt;sequence>
 *         &lt;element name="depositDate" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericDateType"/>
 *         &lt;element name="depositCountry" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="unappliedReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="depositReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fxExecutedDetail" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}FXExecutedRateType" minOccurs="0"/>
 *         &lt;element name="amountDepositedByUser" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *         &lt;element name="amountDepositedToMerchant" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDepositDetailType", propOrder = {
    "depositDate",
    "depositCountry",
    "unappliedReason",
    "depositReference",
    "fxExecutedDetail",
    "amountDepositedByUser",
    "amountDepositedToMerchant"
})
public class UserDepositDetailType
    extends UserDepositType
{

    @XmlElement(required = true)
    protected XMLGregorianCalendar depositDate;
    @XmlElement(required = true)
    protected String depositCountry;
    protected String unappliedReason;
    protected String depositReference;
    protected FXExecutedRateType fxExecutedDetail;
    @XmlElement(required = true)
    protected MonetaryValueType amountDepositedByUser;
    @XmlElement(required = true)
    protected MonetaryValueType amountDepositedToMerchant;

    /**
     * Gets the value of the depositDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepositDate() {
        return depositDate;
    }

    /**
     * Sets the value of the depositDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepositDate(XMLGregorianCalendar value) {
        this.depositDate = value;
    }

    /**
     * Gets the value of the depositCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositCountry() {
        return depositCountry;
    }

    /**
     * Sets the value of the depositCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositCountry(String value) {
        this.depositCountry = value;
    }

    /**
     * Gets the value of the unappliedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnappliedReason() {
        return unappliedReason;
    }

    /**
     * Sets the value of the unappliedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnappliedReason(String value) {
        this.unappliedReason = value;
    }

    /**
     * Gets the value of the depositReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositReference() {
        return depositReference;
    }

    /**
     * Sets the value of the depositReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositReference(String value) {
        this.depositReference = value;
    }

    /**
     * Gets the value of the fxExecutedDetail property.
     * 
     * @return
     *     possible object is
     *     {@link FXExecutedRateType }
     *     
     */
    public FXExecutedRateType getFxExecutedDetail() {
        return fxExecutedDetail;
    }

    /**
     * Sets the value of the fxExecutedDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXExecutedRateType }
     *     
     */
    public void setFxExecutedDetail(FXExecutedRateType value) {
        this.fxExecutedDetail = value;
    }

    /**
     * Gets the value of the amountDepositedByUser property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getAmountDepositedByUser() {
        return amountDepositedByUser;
    }

    /**
     * Sets the value of the amountDepositedByUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setAmountDepositedByUser(MonetaryValueType value) {
        this.amountDepositedByUser = value;
    }

    /**
     * Gets the value of the amountDepositedToMerchant property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getAmountDepositedToMerchant() {
        return amountDepositedToMerchant;
    }

    /**
     * Sets the value of the amountDepositedToMerchant property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setAmountDepositedToMerchant(MonetaryValueType value) {
        this.amountDepositedToMerchant = value;
    }

}
