//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.common.financialtransaction;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.earthport.bind.v1.common.payoutbase.PayoutDetailsType;
import com.earthport.bind.v2.common.core.FXExecutedRateType;
import com.earthport.bind.v2.common.core.MonetaryValueType;
import com.earthport.bind.v2.common.core.RefundPayoutIDType;
import com.earthport.bind.v2.common.identitybase.PayerIdentityType;


/**
 * 
 * 				A financial transaction representing payment to a 
 * 				beneficiary wallet from an account held in the EPS system.
 * 				This element contains all details pertaining to this financial transaction.
 * 			
 * 
 * <p>Java class for WalletPaymentTransactionDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WalletPaymentTransactionDetailType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v4/components/financialTransactionBase}WalletPaymentTransactionType">
 *       &lt;sequence>
 *         &lt;element name="fxExecutedDetail" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}FXExecutedRateType" minOccurs="0"/>
 *         &lt;element name="payoutRequestAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *         &lt;element name="settlementInstructionAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *         &lt;element name="beneficiaryStatementNarrative" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericDescriptionType" minOccurs="0"/>
 *         &lt;element name="payoutDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}PayoutDetailsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="beneficiaryWalletCountry" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="beneficiaryWalletCurrency" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CurrencyCodeType"/>
 *         &lt;element name="refundPayoutID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}RefundPayoutIDType" minOccurs="0"/>
 *         &lt;element name="debitValueDate" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericTimestampType"/>
 *         &lt;element name="payerIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}PayerIdentityType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WalletPaymentTransactionDetailType", propOrder = {
    "fxExecutedDetail",
    "payoutRequestAmount",
    "settlementInstructionAmount",
    "beneficiaryStatementNarrative",
    "payoutDetails",
    "beneficiaryWalletCountry",
    "beneficiaryWalletCurrency",
    "refundPayoutID",
    "debitValueDate",
    "payerIdentity"
})
public class WalletPaymentTransactionDetailType
    extends WalletPaymentTransactionType
{

    protected FXExecutedRateType fxExecutedDetail;
    @XmlElement(required = true)
    protected MonetaryValueType payoutRequestAmount;
    @XmlElement(required = true)
    protected MonetaryValueType settlementInstructionAmount;
    protected String beneficiaryStatementNarrative;
    protected List<PayoutDetailsType> payoutDetails;
    @XmlElement(required = true)
    protected String beneficiaryWalletCountry;
    @XmlElement(required = true)
    protected String beneficiaryWalletCurrency;
    protected RefundPayoutIDType refundPayoutID;
    @XmlElement(required = true)
    protected XMLGregorianCalendar debitValueDate;
    @XmlElement(required = true)
    protected PayerIdentityType payerIdentity;

    /**
     * Gets the value of the fxExecutedDetail property.
     * 
     * @return
     *     possible object is
     *     {@link FXExecutedRateType }
     *     
     */
    public FXExecutedRateType getFxExecutedDetail() {
        return fxExecutedDetail;
    }

    /**
     * Sets the value of the fxExecutedDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXExecutedRateType }
     *     
     */
    public void setFxExecutedDetail(FXExecutedRateType value) {
        this.fxExecutedDetail = value;
    }

    /**
     * Gets the value of the payoutRequestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getPayoutRequestAmount() {
        return payoutRequestAmount;
    }

    /**
     * Sets the value of the payoutRequestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setPayoutRequestAmount(MonetaryValueType value) {
        this.payoutRequestAmount = value;
    }

    /**
     * Gets the value of the settlementInstructionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getSettlementInstructionAmount() {
        return settlementInstructionAmount;
    }

    /**
     * Sets the value of the settlementInstructionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setSettlementInstructionAmount(MonetaryValueType value) {
        this.settlementInstructionAmount = value;
    }

    /**
     * Gets the value of the beneficiaryStatementNarrative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryStatementNarrative() {
        return beneficiaryStatementNarrative;
    }

    /**
     * Sets the value of the beneficiaryStatementNarrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryStatementNarrative(String value) {
        this.beneficiaryStatementNarrative = value;
    }

    /**
     * Gets the value of the payoutDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payoutDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayoutDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayoutDetailsType }
     * 
     * 
     */
    public List<PayoutDetailsType> getPayoutDetails() {
        if (payoutDetails == null) {
            payoutDetails = new ArrayList<PayoutDetailsType>();
        }
        return this.payoutDetails;
    }

    /**
     * Gets the value of the beneficiaryWalletCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryWalletCountry() {
        return beneficiaryWalletCountry;
    }

    /**
     * Sets the value of the beneficiaryWalletCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryWalletCountry(String value) {
        this.beneficiaryWalletCountry = value;
    }

    /**
     * Gets the value of the beneficiaryWalletCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryWalletCurrency() {
        return beneficiaryWalletCurrency;
    }

    /**
     * Sets the value of the beneficiaryWalletCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryWalletCurrency(String value) {
        this.beneficiaryWalletCurrency = value;
    }

    /**
     * Gets the value of the refundPayoutID property.
     * 
     * @return
     *     possible object is
     *     {@link RefundPayoutIDType }
     *     
     */
    public RefundPayoutIDType getRefundPayoutID() {
        return refundPayoutID;
    }

    /**
     * Sets the value of the refundPayoutID property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundPayoutIDType }
     *     
     */
    public void setRefundPayoutID(RefundPayoutIDType value) {
        this.refundPayoutID = value;
    }

    /**
     * Gets the value of the debitValueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDebitValueDate() {
        return debitValueDate;
    }

    /**
     * Sets the value of the debitValueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDebitValueDate(XMLGregorianCalendar value) {
        this.debitValueDate = value;
    }

    /**
     * Gets the value of the payerIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIdentityType }
     *     
     */
    public PayerIdentityType getPayerIdentity() {
        return payerIdentity;
    }

    /**
     * Sets the value of the payerIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIdentityType }
     *     
     */
    public void setPayerIdentity(PayerIdentityType value) {
        this.payerIdentity = value;
    }

}
