//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Holds details of an executed FX conversion that has occured as part of a financial transaction. The FX that occured was from the sellCurrency to the buyCurrency at a particular rate.
 * The rate may have been requested via an FX Quote (fxTicketID).
 * An FX conversion fee may have been applied to certain transaction types. 
 * 
 * <p>Java class for FXExecutedRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FXExecutedRateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fxRate" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}FXRateType"/>
 *         &lt;element name="fxFeeAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="fxTicketID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}FXTicketIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FXExecutedRateType", propOrder = {
    "fxRate",
    "fxFeeAmount",
    "fxTicketID"
})
public class FXExecutedRateType {

    @XmlElement(required = true)
    protected FXRateType fxRate;
    protected MonetaryValueType fxFeeAmount;
    protected FXTicketIDType fxTicketID;

    /**
     * Gets the value of the fxRate property.
     * 
     * @return
     *     possible object is
     *     {@link FXRateType }
     *     
     */
    public FXRateType getFxRate() {
        return fxRate;
    }

    /**
     * Sets the value of the fxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXRateType }
     *     
     */
    public void setFxRate(FXRateType value) {
        this.fxRate = value;
    }

    /**
     * Gets the value of the fxFeeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getFxFeeAmount() {
        return fxFeeAmount;
    }

    /**
     * Sets the value of the fxFeeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setFxFeeAmount(MonetaryValueType value) {
        this.fxFeeAmount = value;
    }

    /**
     * Gets the value of the fxTicketID property.
     * 
     * @return
     *     possible object is
     *     {@link FXTicketIDType }
     *     
     */
    public FXTicketIDType getFxTicketID() {
        return fxTicketID;
    }

    /**
     * Sets the value of the fxTicketID property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXTicketIDType }
     *     
     */
    public void setFxTicketID(FXTicketIDType value) {
        this.fxTicketID = value;
    }

}
