//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.core;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v2.common.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v2.common.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FXTicketIDType }
     * 
     */
    public FXTicketIDType createFXTicketIDType() {
        return new FXTicketIDType();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link FXRateType }
     * 
     */
    public FXRateType createFXRateType() {
        return new FXRateType();
    }

    /**
     * Create an instance of {@link FXExecutedRateType }
     * 
     */
    public FXExecutedRateType createFXExecutedRateType() {
        return new FXExecutedRateType();
    }

    /**
     * Create an instance of {@link RefundPayoutIDType }
     * 
     */
    public RefundPayoutIDType createRefundPayoutIDType() {
        return new RefundPayoutIDType();
    }

    /**
     * Create an instance of {@link UserIDType }
     * 
     */
    public UserIDType createUserIDType() {
        return new UserIDType();
    }

    /**
     * Create an instance of {@link MonetaryValueType }
     * 
     */
    public MonetaryValueType createMonetaryValueType() {
        return new MonetaryValueType();
    }

    /**
     * Create an instance of {@link ReasonType }
     * 
     */
    public ReasonType createReasonType() {
        return new ReasonType();
    }

    /**
     * Create an instance of {@link PaginationResultType }
     * 
     */
    public PaginationResultType createPaginationResultType() {
        return new PaginationResultType();
    }

    /**
     * Create an instance of {@link MonetaryBalanceType }
     * 
     */
    public MonetaryBalanceType createMonetaryBalanceType() {
        return new MonetaryBalanceType();
    }

    /**
     * Create an instance of {@link FXDetailType }
     * 
     */
    public FXDetailType createFXDetailType() {
        return new FXDetailType();
    }

    /**
     * Create an instance of {@link BeneficiaryIdentityIDType }
     * 
     */
    public BeneficiaryIdentityIDType createBeneficiaryIdentityIDType() {
        return new BeneficiaryIdentityIDType();
    }

    /**
     * Create an instance of {@link SortCriteriaType }
     * 
     */
    public SortCriteriaType createSortCriteriaType() {
        return new SortCriteriaType();
    }

}
