//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.validatePayerIdentity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v1.validatePayerIdentity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidatePayerIdentityResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v1/services/validatePayerIdentity", "validatePayerIdentityResponse");
    private final static QName _ValidatePayerIdentity_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v1/services/validatePayerIdentity", "validatePayerIdentity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v1.validatePayerIdentity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidatePayerIdentityType }
     * 
     */
    public ValidatePayerIdentityType createValidatePayerIdentityType() {
        return new ValidatePayerIdentityType();
    }

    /**
     * Create an instance of {@link ValidatePayerIdentityResponseType }
     * 
     */
    public ValidatePayerIdentityResponseType createValidatePayerIdentityResponseType() {
        return new ValidatePayerIdentityResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePayerIdentityResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v1/services/validatePayerIdentity", name = "validatePayerIdentityResponse")
    public JAXBElement<ValidatePayerIdentityResponseType> createValidatePayerIdentityResponse(ValidatePayerIdentityResponseType value) {
        return new JAXBElement<ValidatePayerIdentityResponseType>(_ValidatePayerIdentityResponse_QNAME, ValidatePayerIdentityResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidatePayerIdentityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v1/services/validatePayerIdentity", name = "validatePayerIdentity")
    public JAXBElement<ValidatePayerIdentityType> createValidatePayerIdentity(ValidatePayerIdentityType value) {
        return new JAXBElement<ValidatePayerIdentityType>(_ValidatePayerIdentity_QNAME, ValidatePayerIdentityType.class, null, value);
    }

}
