//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.validatePayerIdentity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidatePayerIdentityResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidatePayerIdentityResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="isPayerIdentityValid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidatePayerIdentityResponseType", propOrder = {

})
public class ValidatePayerIdentityResponseType {

    protected boolean isPayerIdentityValid;

    /**
     * Gets the value of the isPayerIdentityValid property.
     * 
     */
    public boolean isIsPayerIdentityValid() {
        return isPayerIdentityValid;
    }

    /**
     * Sets the value of the isPayerIdentityValid property.
     * 
     */
    public void setIsPayerIdentityValid(boolean value) {
        this.isPayerIdentityValid = value;
    }

}
