//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.identityFieldsBase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This type defines that in common case at least one of the nested groups
 *                 should be included into addBeneficiaryBankAccount request document.
 *                 On UI it can be presented with drop-down list containing nested groups labels.
 *                 'minElementNum' minimum this number of the nested groups should be specified (1 by default).
 *                 'maxElementNum' maximum this number of the nested groups can be specified (1 by default).
 *             
 * 
 * <p>Java class for BeneficiaryIdentityFieldGroupChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryIdentityFieldGroupChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="beneficiaryIdentityFieldGroupsList" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/identityFieldsBase}BeneficiaryIdentityGroupsListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="minGroupsListNum" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="maxGroupsListNum" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryIdentityFieldGroupChoiceType", propOrder = {
    "beneficiaryIdentityFieldGroupsList"
})
public class BeneficiaryIdentityFieldGroupChoiceType {

    protected List<BeneficiaryIdentityGroupsListType> beneficiaryIdentityFieldGroupsList;
    @XmlAttribute(name = "minGroupsListNum")
    protected Integer minGroupsListNum;
    @XmlAttribute(name = "maxGroupsListNum")
    protected Integer maxGroupsListNum;

    /**
     * Gets the value of the beneficiaryIdentityFieldGroupsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beneficiaryIdentityFieldGroupsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeneficiaryIdentityFieldGroupsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeneficiaryIdentityGroupsListType }
     * 
     * 
     */
    public List<BeneficiaryIdentityGroupsListType> getBeneficiaryIdentityFieldGroupsList() {
        if (beneficiaryIdentityFieldGroupsList == null) {
            beneficiaryIdentityFieldGroupsList = new ArrayList<BeneficiaryIdentityGroupsListType>();
        }
        return this.beneficiaryIdentityFieldGroupsList;
    }

    /**
     * Gets the value of the minGroupsListNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMinGroupsListNum() {
        if (minGroupsListNum == null) {
            return  1;
        } else {
            return minGroupsListNum;
        }
    }

    /**
     * Sets the value of the minGroupsListNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinGroupsListNum(Integer value) {
        this.minGroupsListNum = value;
    }

    /**
     * Gets the value of the maxGroupsListNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxGroupsListNum() {
        if (maxGroupsListNum == null) {
            return  1;
        } else {
            return maxGroupsListNum;
        }
    }

    /**
     * Sets the value of the maxGroupsListNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxGroupsListNum(Integer value) {
        this.maxGroupsListNum = value;
    }

}
