//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.getTransactionDetail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				An EPS and/or Merchant transaction ID that uniquely identifies
 * 				a transaction in the EPS system
 *         	
 * 
 * <p>Java class for TransactionIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="epTransactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}PaymentIDType" minOccurs="0"/>
 *         &lt;element name="merchantTransactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantTransactionRefType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionIDType", propOrder = {
    "epTransactionID",
    "merchantTransactionID"
})
public class TransactionIDType {

    protected Long epTransactionID;
    protected String merchantTransactionID;

    /**
     * Gets the value of the epTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEpTransactionID() {
        return epTransactionID;
    }

    /**
     * Sets the value of the epTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEpTransactionID(Long value) {
        this.epTransactionID = value;
    }

    /**
     * Gets the value of the merchantTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTransactionID() {
        return merchantTransactionID;
    }

    /**
     * Sets the value of the merchantTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTransactionID(String value) {
        this.merchantTransactionID = value;
    }

}
