//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.getTransactionDetail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v4.common.financialtransaction.FinancialTransactionType;


/**
 * <p>Java class for TransactionDetailMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDetailMappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v4/services/getTransactionDetail}TransactionIDType"/>
 *         &lt;element name="transactionDetail" type="{http://customer.endpoint.earthport.com/api/merchant/v4/components/financialTransactionBase}FinancialTransactionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDetailMappingType", propOrder = {
    "transactionID",
    "transactionDetail"
})
public class TransactionDetailMappingType {

    @XmlElement(required = true)
    protected TransactionIDType transactionID;
    @XmlElement(required = true)
    protected FinancialTransactionType transactionDetail;

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionIDType }
     *     
     */
    public TransactionIDType getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionIDType }
     *     
     */
    public void setTransactionID(TransactionIDType value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the transactionDetail property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialTransactionType }
     *     
     */
    public FinancialTransactionType getTransactionDetail() {
        return transactionDetail;
    }

    /**
     * Sets the value of the transactionDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialTransactionType }
     *     
     */
    public void setTransactionDetail(FinancialTransactionType value) {
        this.transactionDetail = value;
    }

}
