//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.common.bankbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Each beneficiaryBankAccountField would normally be displayed 
 * 				in the UI from left to right based on the tabOrder attribute.
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;br xmlns="http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase" xmlns:epcore="http://customer.endpoint.earthport.com/api/merchant/v2/components/core" xmlns:epident="http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/&gt;
 * </pre>
 * 
 * 				The beneficiaryBankAccountField element contains
 * 				the following attributes:
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ul xmlns="http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase" xmlns:epcore="http://customer.endpoint.earthport.com/api/merchant/v2/components/core" xmlns:epident="http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;&lt;li&gt;tabOrder: indicates the ordering of this field in the UI&lt;/li&gt;&lt;li&gt;parameterName: the name of the corresponding Earthport parameter to use when calling addBeneficiaryBankAcount&lt;/li&gt;&lt;li&gt;displaySize: a suggested field size to display&lt;/li&gt;&lt;li&gt;maxSize: suggested client side syntactic validation rule&lt;/li&gt;&lt;li&gt;description: suggested roll-over or help text description to assist users&lt;/li&gt;&lt;li&gt;separator: the separator to display following (to the right hand side) this field, usually '-' or '/'&lt;/li&gt;&lt;li&gt;inputType: whether this field should be represented as a text field or a list of options&lt;/li&gt;&lt;li&gt;subTitle: if present contains a sub-label to be displayed with the field&lt;/li&gt;&lt;li&gt;locale: the localisation setting of this particular record&lt;/li&gt;&lt;li&gt;value: the current value of this field, populated by the getBeneficiaryBankAccount service&lt;/li&gt;&lt;/ul&gt;
 * </pre>
 * 
 * 
 * <p>Java class for BeneficiaryBankAccountFieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryBankAccountFieldType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listItems" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountListItemsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tabOrder" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="parameterName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="separator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="displaySize" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maxSize" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subTitle" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inputType" use="required" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountFieldInputType" />
 *       &lt;attribute name="locale" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryBankAccountFieldType", propOrder = {
    "listItems"
})
public class BeneficiaryBankAccountFieldType {

    protected BeneficiaryBankAccountListItemsType listItems;
    @XmlAttribute(name = "tabOrder", required = true)
    protected int tabOrder;
    @XmlAttribute(name = "parameterName", required = true)
    protected String parameterName;
    @XmlAttribute(name = "separator", required = true)
    protected String separator;
    @XmlAttribute(name = "displaySize", required = true)
    protected int displaySize;
    @XmlAttribute(name = "maxSize", required = true)
    protected int maxSize;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "subTitle", required = true)
    protected String subTitle;
    @XmlAttribute(name = "inputType", required = true)
    protected BeneficiaryBankAccountFieldInputType inputType;
    @XmlAttribute(name = "locale", required = true)
    protected String locale;
    @XmlAttribute(name = "value")
    protected String value;

    /**
     * Gets the value of the listItems property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryBankAccountListItemsType }
     *     
     */
    public BeneficiaryBankAccountListItemsType getListItems() {
        return listItems;
    }

    /**
     * Sets the value of the listItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryBankAccountListItemsType }
     *     
     */
    public void setListItems(BeneficiaryBankAccountListItemsType value) {
        this.listItems = value;
    }

    /**
     * Gets the value of the tabOrder property.
     * 
     */
    public int getTabOrder() {
        return tabOrder;
    }

    /**
     * Sets the value of the tabOrder property.
     * 
     */
    public void setTabOrder(int value) {
        this.tabOrder = value;
    }

    /**
     * Gets the value of the parameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterName(String value) {
        this.parameterName = value;
    }

    /**
     * Gets the value of the separator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparator() {
        return separator;
    }

    /**
     * Sets the value of the separator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparator(String value) {
        this.separator = value;
    }

    /**
     * Gets the value of the displaySize property.
     * 
     */
    public int getDisplaySize() {
        return displaySize;
    }

    /**
     * Sets the value of the displaySize property.
     * 
     */
    public void setDisplaySize(int value) {
        this.displaySize = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     */
    public int getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     */
    public void setMaxSize(int value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the subTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * Sets the value of the subTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubTitle(String value) {
        this.subTitle = value;
    }

    /**
     * Gets the value of the inputType property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryBankAccountFieldInputType }
     *     
     */
    public BeneficiaryBankAccountFieldInputType getInputType() {
        return inputType;
    }

    /**
     * Sets the value of the inputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryBankAccountFieldInputType }
     *     
     */
    public void setInputType(BeneficiaryBankAccountFieldInputType value) {
        this.inputType = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
