//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.common.bankbase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *   				The beneficiaryBankAccountField contains optional listItem sub-elements.
 * 				The listItem sub-elements would normally be present where the inputType 
 * 				attribute is 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;i xmlns="http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase" xmlns:epcore="http://customer.endpoint.earthport.com/api/merchant/v2/components/core" xmlns:epident="http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;'list'&lt;/i&gt;
 * </pre>
 * . 
 *             
 * 
 * <p>Java class for BeneficiaryBankAccountListItemsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryBankAccountListItemsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beneficiaryBankAccountField" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountListItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryBankAccountListItemsType", propOrder = {
    "beneficiaryBankAccountField"
})
public class BeneficiaryBankAccountListItemsType {

    @XmlElement(required = true)
    protected List<BeneficiaryBankAccountListItemType> beneficiaryBankAccountField;

    /**
     * Gets the value of the beneficiaryBankAccountField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beneficiaryBankAccountField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeneficiaryBankAccountField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeneficiaryBankAccountListItemType }
     * 
     * 
     */
    public List<BeneficiaryBankAccountListItemType> getBeneficiaryBankAccountField() {
        if (beneficiaryBankAccountField == null) {
            beneficiaryBankAccountField = new ArrayList<BeneficiaryBankAccountListItemType>();
        }
        return this.beneficiaryBankAccountField;
    }

}
