//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.common.bankbase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This group consists of a collection of both the
 * 				beneficiary bank ID token and a small set of values summarising the associated 
 * 				beneficiary	bank account.
 * 
 * 				This is used as a return type for the
 * 				listBankSummary service.
 * 			
 * 
 * <p>Java class for BeneficiaryBankAccountSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryBankAccountSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="benBankID" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BenBankIDType"/>
 *         &lt;element name="description" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountDescType"/>
 *         &lt;element name="countryCode" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="bankAccountDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BankAccountDetailsType" maxOccurs="unbounded"/>
 *         &lt;element name="status" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountStatusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryBankAccountSummaryType", propOrder = {
    "benBankID",
    "description",
    "countryCode",
    "bankAccountDetails",
    "status"
})
public class BeneficiaryBankAccountSummaryType {

    @XmlElement(required = true)
    protected BenBankIDType benBankID;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected List<BankAccountDetailsType> bankAccountDetails;
    @XmlElement(required = true)
    protected BeneficiaryBankAccountStatusType status;

    /**
     * Gets the value of the benBankID property.
     * 
     * @return
     *     possible object is
     *     {@link BenBankIDType }
     *     
     */
    public BenBankIDType getBenBankID() {
        return benBankID;
    }

    /**
     * Sets the value of the benBankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenBankIDType }
     *     
     */
    public void setBenBankID(BenBankIDType value) {
        this.benBankID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the bankAccountDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankAccountDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankAccountDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankAccountDetailsType }
     * 
     * 
     */
    public List<BankAccountDetailsType> getBankAccountDetails() {
        if (bankAccountDetails == null) {
            bankAccountDetails = new ArrayList<BankAccountDetailsType>();
        }
        return this.bankAccountDetails;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryBankAccountStatusType }
     *     
     */
    public BeneficiaryBankAccountStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryBankAccountStatusType }
     *     
     */
    public void setStatus(BeneficiaryBankAccountStatusType value) {
        this.status = value;
    }

}
