//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.common.bankbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.core.UserIDType;


/**
 * 
 * 				This group consists of a collection of both the user ID
 * 				group and beneficiary bank ID group.
 * 
 * 				The 'userID' is a collection of user identifier types.
 * 
 * 				The 'benBankID' is a collection of account identifier
 * 				types.
 * 
 * 				Both the 'userID' and 'benBankID' fields are mandatory.
 * 			
 * 
 * <p>Java class for UsersBankIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsersBankIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}UserIDType"/>
 *         &lt;element name="benBankID" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BenBankIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsersBankIDType", propOrder = {
    "userID",
    "benBankID"
})
public class UsersBankIDType {

    @XmlElement(required = true)
    protected UserIDType userID;
    @XmlElement(required = true)
    protected BenBankIDType benBankID;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link UserIDType }
     *     
     */
    public UserIDType getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIDType }
     *     
     */
    public void setUserID(UserIDType value) {
        this.userID = value;
    }

    /**
     * Gets the value of the benBankID property.
     * 
     * @return
     *     possible object is
     *     {@link BenBankIDType }
     *     
     */
    public BenBankIDType getBenBankID() {
        return benBankID;
    }

    /**
     * Sets the value of the benBankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenBankIDType }
     *     
     */
    public void setBenBankID(BenBankIDType value) {
        this.benBankID = value;
    }

}
