//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.sendWalletPayment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v1.sendWalletPayment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendWalletPayment_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v1/sendWalletPayment", "sendWalletPayment");
    private final static QName _SendWalletPaymentResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v1/sendWalletPayment", "sendWalletPaymentResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v1.sendWalletPayment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendWalletPaymentType }
     * 
     */
    public SendWalletPaymentType createSendWalletPaymentType() {
        return new SendWalletPaymentType();
    }

    /**
     * Create an instance of {@link SendWalletPaymentResponseType }
     * 
     */
    public SendWalletPaymentResponseType createSendWalletPaymentResponseType() {
        return new SendWalletPaymentResponseType();
    }

    /**
     * Create an instance of {@link BeneficiaryAmountInformationType }
     * 
     */
    public BeneficiaryAmountInformationType createBeneficiaryAmountInformationType() {
        return new BeneficiaryAmountInformationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendWalletPaymentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v1/sendWalletPayment", name = "sendWalletPayment")
    public JAXBElement<SendWalletPaymentType> createSendWalletPayment(SendWalletPaymentType value) {
        return new JAXBElement<SendWalletPaymentType>(_SendWalletPayment_QNAME, SendWalletPaymentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendWalletPaymentResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v1/sendWalletPayment", name = "sendWalletPaymentResponse")
    public JAXBElement<SendWalletPaymentResponseType> createSendWalletPaymentResponse(SendWalletPaymentResponseType value) {
        return new JAXBElement<SendWalletPaymentResponseType>(_SendWalletPaymentResponse_QNAME, SendWalletPaymentResponseType.class, null, value);
    }

}
