//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://customer.endpoint.earthport.com/api/merchant/v1/sendWalletPayment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.earthport.bind.v1.sendWalletPayment;
