//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.sendWalletPayment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.earthport.bind.v1.common.walletBaseTypes.UsersWalletIDType;
import com.earthport.bind.v2.common.core.FXRateType;
import com.earthport.bind.v2.common.core.MonetaryValueType;


/**
 * <p>Java class for sendWalletPaymentResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sendWalletPaymentResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usersWalletID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}UsersWalletIDType"/>
 *         &lt;element name="paymentID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}PaymentIDType"/>
 *         &lt;element name="merchantTransactionReference" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantTransactionRefType"/>
 *         &lt;element name="feeValue" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="fxRate" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}FXRateType" minOccurs="0"/>
 *         &lt;element name="liquidityValue" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *         &lt;element name="settlementValue" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="acceptedDate" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericTimestampType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendWalletPaymentResponseType", propOrder = {
    "usersWalletID",
    "paymentID",
    "merchantTransactionReference",
    "feeValue",
    "fxRate",
    "liquidityValue",
    "settlementValue",
    "acceptedDate"
})
public class SendWalletPaymentResponseType {

    @XmlElement(required = true)
    protected UsersWalletIDType usersWalletID;
    protected long paymentID;
    @XmlElement(required = true)
    protected String merchantTransactionReference;
    protected MonetaryValueType feeValue;
    protected FXRateType fxRate;
    @XmlElement(required = true)
    protected MonetaryValueType liquidityValue;
    protected MonetaryValueType settlementValue;
    protected XMLGregorianCalendar acceptedDate;

    /**
     * Gets the value of the usersWalletID property.
     * 
     * @return
     *     possible object is
     *     {@link UsersWalletIDType }
     *     
     */
    public UsersWalletIDType getUsersWalletID() {
        return usersWalletID;
    }

    /**
     * Sets the value of the usersWalletID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersWalletIDType }
     *     
     */
    public void setUsersWalletID(UsersWalletIDType value) {
        this.usersWalletID = value;
    }

    /**
     * Gets the value of the paymentID property.
     * 
     */
    public long getPaymentID() {
        return paymentID;
    }

    /**
     * Sets the value of the paymentID property.
     * 
     */
    public void setPaymentID(long value) {
        this.paymentID = value;
    }

    /**
     * Gets the value of the merchantTransactionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTransactionReference() {
        return merchantTransactionReference;
    }

    /**
     * Sets the value of the merchantTransactionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTransactionReference(String value) {
        this.merchantTransactionReference = value;
    }

    /**
     * Gets the value of the feeValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getFeeValue() {
        return feeValue;
    }

    /**
     * Sets the value of the feeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setFeeValue(MonetaryValueType value) {
        this.feeValue = value;
    }

    /**
     * Gets the value of the fxRate property.
     * 
     * @return
     *     possible object is
     *     {@link FXRateType }
     *     
     */
    public FXRateType getFxRate() {
        return fxRate;
    }

    /**
     * Sets the value of the fxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXRateType }
     *     
     */
    public void setFxRate(FXRateType value) {
        this.fxRate = value;
    }

    /**
     * Gets the value of the liquidityValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getLiquidityValue() {
        return liquidityValue;
    }

    /**
     * Sets the value of the liquidityValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setLiquidityValue(MonetaryValueType value) {
        this.liquidityValue = value;
    }

    /**
     * Gets the value of the settlementValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getSettlementValue() {
        return settlementValue;
    }

    /**
     * Sets the value of the settlementValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setSettlementValue(MonetaryValueType value) {
        this.settlementValue = value;
    }

    /**
     * Gets the value of the acceptedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcceptedDate() {
        return acceptedDate;
    }

    /**
     * Sets the value of the acceptedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcceptedDate(XMLGregorianCalendar value) {
        this.acceptedDate = value;
    }

}
