//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.validateBeneficiaryBankAccount;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v3.common.bankbase.BeneficiaryBankAccountType;


/**
 * <p>Java class for ValidateBeneficiaryBankAccountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidateBeneficiaryBankAccountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beneficiaryBankAccount" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidateBeneficiaryBankAccountType", propOrder = {
    "beneficiaryBankAccount"
})
public class ValidateBeneficiaryBankAccountType {

    @XmlElement(required = true)
    protected BeneficiaryBankAccountType beneficiaryBankAccount;
    @XmlAttribute(name = "version", required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the beneficiaryBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryBankAccountType }
     *     
     */
    public BeneficiaryBankAccountType getBeneficiaryBankAccount() {
        return beneficiaryBankAccount;
    }

    /**
     * Sets the value of the beneficiaryBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryBankAccountType }
     *     
     */
    public void setBeneficiaryBankAccount(BeneficiaryBankAccountType value) {
        this.beneficiaryBankAccount = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
