//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.errorResponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *                 XML response root element type where web service call was not
 *                 successful.
 *             
 * 
 * <p>Java class for ErrorResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErrorResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeOfFailure" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="failureType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}ErrorResponseCategoryType"/>
 *         &lt;element name="shortMsg" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}ShortMessageType"/>
 *         &lt;element name="longMsg" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}LongMessageType" minOccurs="0"/>
 *         &lt;element name="code" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}CodeType"/>
 *         &lt;element name="uniqueErrorID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}ErrorIDType" minOccurs="0"/>
 *         &lt;element name="correlationID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}CorrelationIDType" minOccurs="0"/>
 *         &lt;element name="earthportID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}EarthportIDType" minOccurs="0"/>
 *         &lt;element name="failures" type="{http://customer.endpoint.earthport.com/api/merchant/v1/error}FailuresType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorResponseType", propOrder = {
    "timeOfFailure",
    "failureType",
    "shortMsg",
    "longMsg",
    "code",
    "uniqueErrorID",
    "correlationID",
    "earthportID",
    "failures"
})
public class ErrorResponseType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeOfFailure;
    @XmlElement(required = true)
    protected ErrorResponseCategoryType failureType;
    @XmlElement(required = true)
    protected String shortMsg;
    protected String longMsg;
    protected int code;
    protected String uniqueErrorID;
    protected String correlationID;
    protected String earthportID;
    @XmlElementRef(name = "failures", namespace = "http://customer.endpoint.earthport.com/api/merchant/v1/error", type = JAXBElement.class)
    protected JAXBElement<FailuresType> failures;

    /**
     * Gets the value of the timeOfFailure property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfFailure() {
        return timeOfFailure;
    }

    /**
     * Sets the value of the timeOfFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfFailure(XMLGregorianCalendar value) {
        this.timeOfFailure = value;
    }

    /**
     * Gets the value of the failureType property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorResponseCategoryType }
     *     
     */
    public ErrorResponseCategoryType getFailureType() {
        return failureType;
    }

    /**
     * Sets the value of the failureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorResponseCategoryType }
     *     
     */
    public void setFailureType(ErrorResponseCategoryType value) {
        this.failureType = value;
    }

    /**
     * Gets the value of the shortMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortMsg() {
        return shortMsg;
    }

    /**
     * Sets the value of the shortMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortMsg(String value) {
        this.shortMsg = value;
    }

    /**
     * Gets the value of the longMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongMsg() {
        return longMsg;
    }

    /**
     * Sets the value of the longMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongMsg(String value) {
        this.longMsg = value;
    }

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCode(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the uniqueErrorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueErrorID() {
        return uniqueErrorID;
    }

    /**
     * Sets the value of the uniqueErrorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueErrorID(String value) {
        this.uniqueErrorID = value;
    }

    /**
     * Gets the value of the correlationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationID(String value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the earthportID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarthportID() {
        return earthportID;
    }

    /**
     * Sets the value of the earthportID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarthportID(String value) {
        this.earthportID = value;
    }

    /**
     * Gets the value of the failures property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FailuresType }{@code >}
     *     
     */
    public JAXBElement<FailuresType> getFailures() {
        return failures;
    }

    /**
     * Sets the value of the failures property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FailuresType }{@code >}
     *     
     */
    public void setFailures(JAXBElement<FailuresType> value) {
        this.failures = ((JAXBElement<FailuresType> ) value);
    }

}
