//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.walletBaseTypes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v1.common.walletBaseTypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v1.common.walletBaseTypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WalletListItemType }
     * 
     */
    public WalletListItemType createWalletListItemType() {
        return new WalletListItemType();
    }

    /**
     * Create an instance of {@link WalletType }
     * 
     */
    public WalletType createWalletType() {
        return new WalletType();
    }

    /**
     * Create an instance of {@link UserWalletType }
     * 
     */
    public UserWalletType createUserWalletType() {
        return new UserWalletType();
    }

    /**
     * Create an instance of {@link WalletGroupsListType }
     * 
     */
    public WalletGroupsListType createWalletGroupsListType() {
        return new WalletGroupsListType();
    }

    /**
     * Create an instance of {@link WalletDetailsType }
     * 
     */
    public WalletDetailsType createWalletDetailsType() {
        return new WalletDetailsType();
    }

    /**
     * Create an instance of {@link WalletFieldsListType }
     * 
     */
    public WalletFieldsListType createWalletFieldsListType() {
        return new WalletFieldsListType();
    }

    /**
     * Create an instance of {@link WalletFieldType }
     * 
     */
    public WalletFieldType createWalletFieldType() {
        return new WalletFieldType();
    }

    /**
     * Create an instance of {@link WalletIDType }
     * 
     */
    public WalletIDType createWalletIDType() {
        return new WalletIDType();
    }

    /**
     * Create an instance of {@link WalletSummaryType }
     * 
     */
    public WalletSummaryType createWalletSummaryType() {
        return new WalletSummaryType();
    }

    /**
     * Create an instance of {@link WalletListItemsType }
     * 
     */
    public WalletListItemsType createWalletListItemsType() {
        return new WalletListItemsType();
    }

    /**
     * Create an instance of {@link WalletGroupType }
     * 
     */
    public WalletGroupType createWalletGroupType() {
        return new WalletGroupType();
    }

    /**
     * Create an instance of {@link UsersWalletIDType }
     * 
     */
    public UsersWalletIDType createUsersWalletIDType() {
        return new UsersWalletIDType();
    }

}
