//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.walletBaseTypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.core.UserIDType;


/**
 * 
 *                 This group consists of a collection of both the user ID
 *                 group and wallet ID group.
 * 
 *                 The 'userID' is a collection of user identifier types.
 * 
 *                 The 'walletID' is a collection of wallet identifier
 *                 types.
 * 
 *                 Both the 'userID' and 'walletID' fields are mandatory.
 *             
 * 
 * <p>Java class for UsersWalletIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UsersWalletIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}UserIDType"/>
 *         &lt;element name="walletID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsersWalletIDType", propOrder = {
    "userID",
    "walletID"
})
public class UsersWalletIDType {

    @XmlElement(required = true)
    protected UserIDType userID;
    @XmlElement(required = true)
    protected WalletIDType walletID;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link UserIDType }
     *     
     */
    public UserIDType getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIDType }
     *     
     */
    public void setUserID(UserIDType value) {
        this.userID = value;
    }

    /**
     * Gets the value of the walletID property.
     * 
     * @return
     *     possible object is
     *     {@link WalletIDType }
     *     
     */
    public WalletIDType getWalletID() {
        return walletID;
    }

    /**
     * Sets the value of the walletID property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletIDType }
     *     
     */
    public void setWalletID(WalletIDType value) {
        this.walletID = value;
    }

}
