//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.walletBaseTypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This group consists of a collection of both the
 *                 wallet ID token and associated beneficiary
 *                 wallet group.
 * 
 *                 This is used as a return type for the
 *                 listActiveWallet service.
 *             
 * 
 * <p>Java class for userWalletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userWalletType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="walletID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletIDType"/>
 *         &lt;element name="wallet" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userWalletType", propOrder = {
    "walletID",
    "wallet"
})
public class UserWalletType {

    @XmlElement(required = true)
    protected WalletIDType walletID;
    @XmlElement(required = true)
    protected WalletType wallet;

    /**
     * Gets the value of the walletID property.
     * 
     * @return
     *     possible object is
     *     {@link WalletIDType }
     *     
     */
    public WalletIDType getWalletID() {
        return walletID;
    }

    /**
     * Sets the value of the walletID property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletIDType }
     *     
     */
    public void setWalletID(WalletIDType value) {
        this.walletID = value;
    }

    /**
     * Gets the value of the wallet property.
     * 
     * @return
     *     possible object is
     *     {@link WalletType }
     *     
     */
    public WalletType getWallet() {
        return wallet;
    }

    /**
     * Sets the value of the wallet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletType }
     *     
     */
    public void setWallet(WalletType value) {
        this.wallet = value;
    }

}
