//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.walletBaseTypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.identitybase.BeneficiaryIdentityType;


/**
 * 
 *                 This type provides all the possible information required
 *                 to identify a wallet.
 * 
 *                 The identity of the beneficiary of this wallet is
 *                 mandatory and must be supplied in the
 *                 'beneficiaryIdentity' field.
 * 
 *                 A description of this wallet is optional and may
 *                 be supplied in the 'description' field.
 * 
 *                 The territory in which this wallet is domiciled is
 *                 mandatory and must be supplied in the 'countryCode'
 *                 field as a 2 character country code.
 * 
 *                 The currency held in this wallet is mandatory and must
 *                 be supplied in the 'currencyCode' field as a 3 character
 *                 currency code.
 * 
 *                 The mandatory 'walletDetails' is a group of
 *                 sub-elements which collectively identify the wallet.
 *             
 * 
 * <p>Java class for walletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="walletType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beneficiaryIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}BeneficiaryIdentityType"/>
 *         &lt;element name="description" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletDescType" minOccurs="0"/>
 *         &lt;element name="countryCode" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="currencyCode" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CurrencyCodeType"/>
 *         &lt;element name="walletDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletDetailsType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "walletType", propOrder = {
    "beneficiaryIdentity",
    "description",
    "countryCode",
    "currencyCode",
    "walletDetails"
})
public class WalletType {

    @XmlElement(required = true)
    protected BeneficiaryIdentityType beneficiaryIdentity;
    protected String description;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected String currencyCode;
    @XmlElement(required = true)
    protected List<WalletDetailsType> walletDetails;

    /**
     * Gets the value of the beneficiaryIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryIdentityType }
     *     
     */
    public BeneficiaryIdentityType getBeneficiaryIdentity() {
        return beneficiaryIdentity;
    }

    /**
     * Sets the value of the beneficiaryIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryIdentityType }
     *     
     */
    public void setBeneficiaryIdentity(BeneficiaryIdentityType value) {
        this.beneficiaryIdentity = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the walletDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the walletDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWalletDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WalletDetailsType }
     * 
     * 
     */
    public List<WalletDetailsType> getWalletDetails() {
        if (walletDetails == null) {
            walletDetails = new ArrayList<WalletDetailsType>();
        }
        return this.walletDetails;
    }

}
