//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.walletBaseTypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This group consists of a collection of both the
 *                 wallet ID token and a small set of values summarising the associated
 *                 wallet.
 * 
 *                 This is used as a return type for the
 *                 listWalletSummary service.
 *             
 * 
 * <p>Java class for walletSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="walletSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="walletID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletIDType"/>
 *         &lt;element name="description" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletDescType"/>
 *         &lt;element name="countryCode" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="walletDetails" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletDetailsType" maxOccurs="unbounded"/>
 *         &lt;element name="status" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletStatusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "walletSummaryType", propOrder = {
    "walletID",
    "description",
    "countryCode",
    "walletDetails",
    "status"
})
public class WalletSummaryType {

    @XmlElement(required = true)
    protected WalletIDType walletID;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected List<WalletDetailsType> walletDetails;
    @XmlElement(required = true)
    protected WalletStatusType status;

    /**
     * Gets the value of the walletID property.
     * 
     * @return
     *     possible object is
     *     {@link WalletIDType }
     *     
     */
    public WalletIDType getWalletID() {
        return walletID;
    }

    /**
     * Sets the value of the walletID property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletIDType }
     *     
     */
    public void setWalletID(WalletIDType value) {
        this.walletID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the walletDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the walletDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWalletDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WalletDetailsType }
     * 
     * 
     */
    public List<WalletDetailsType> getWalletDetails() {
        if (walletDetails == null) {
            walletDetails = new ArrayList<WalletDetailsType>();
        }
        return this.walletDetails;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link WalletStatusType }
     *     
     */
    public WalletStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletStatusType }
     *     
     */
    public void setStatus(WalletStatusType value) {
        this.status = value;
    }

}
