//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.walletBaseTypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns="http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase" xmlns:epcore="http://customer.endpoint.earthport.com/api/merchant/v2/components/core" xmlns:epident="http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 *                     This group holds all possible account identifier
 *                     types - listed below in alphabetical order. The data which should be supplied in this group
 *                     differs depending on the wallet type. Please
 *                     refer to the integration guide for type-specific
 *                     details of what should be supplied.
 *                 &lt;/p&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns="http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase" xmlns:epcore="http://customer.endpoint.earthport.com/api/merchant/v2/components/core" xmlns:epident="http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 *                     The following set of parameter names are valid 'keys':
 *                     &lt;ul&gt;&lt;li&gt;MSISDN&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;
 * </pre>
 * 
 * 
 * <p>Java class for walletDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="walletDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="key" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletDetailsKeyType"/>
 *         &lt;element name="value" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/walletBase}walletDetailsValueType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "walletDetailsType", propOrder = {
    "key",
    "value"
})
public class WalletDetailsType {

    @XmlElement(required = true)
    protected String key;
    @XmlElement(required = true)
    protected String value;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
