//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.payoutbase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PayerType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="authenticatedCaller"/>
 *     &lt;enumeration value="managedMerchant"/>
 *     &lt;enumeration value="user"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PayerType")
@XmlEnum
public enum PayerType {

    @XmlEnumValue("authenticatedCaller")
    AUTHENTICATED_CALLER("authenticatedCaller"),
    @XmlEnumValue("managedMerchant")
    MANAGED_MERCHANT("managedMerchant"),
    @XmlEnumValue("user")
    USER("user");
    private final String value;

    PayerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PayerType fromValue(String v) {
        for (PayerType c: PayerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
