//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The identity of a beneficiary legal entity.
 * 
 * 				The 'legalEntityName' attribute is mandatory.
 * 				The
 * 				'legalEntityRegistration' attribute is an optional attribute.
 * 				The 'address' is an optional attribute.
 * 			
 * 
 * <p>Java class for BeneficiaryLegalEntityIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryLegalEntityIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="legalEntityName" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}LegalEntityNameType"/>
 *         &lt;element name="legalEntityRegistration" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}LegalEntityRegistrationType" minOccurs="0"/>
 *         &lt;element name="address" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}AddressType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryLegalEntityIdentityType", propOrder = {
    "legalEntityName",
    "legalEntityRegistration",
    "address"
})
public class BeneficiaryLegalEntityIdentityType {

    @XmlElement(required = true)
    protected String legalEntityName;
    protected LegalEntityRegistrationType legalEntityRegistration;
    protected AddressType address;

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the legalEntityRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntityRegistrationType }
     *     
     */
    public LegalEntityRegistrationType getLegalEntityRegistration() {
        return legalEntityRegistration;
    }

    /**
     * Sets the value of the legalEntityRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntityRegistrationType }
     *     
     */
    public void setLegalEntityRegistration(LegalEntityRegistrationType value) {
        this.legalEntityRegistration = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

}
