//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This group consists of a legal entity registration
 * 				number
 * 				type and the country that the legal entity is registered in.
 * 
 * 				Legal Entity Registration Number is mandatory
 * 				Legal Entity
 * 				Registration Country is mandatory
 * 				Legal Entity Registration Province
 * 				is optional
 * 			
 * 
 * <p>Java class for LegalEntityRegistrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegalEntityRegistrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="legalEntityRegistrationNumber" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}LegalEntityRegistrationNumberType"/>
 *         &lt;element name="legalEntityRegistrationCountry" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="legalEntityRegistrationProvince" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegalEntityRegistrationType", propOrder = {
    "legalEntityRegistrationNumber",
    "legalEntityRegistrationCountry",
    "legalEntityRegistrationProvince"
})
public class LegalEntityRegistrationType {

    @XmlElement(required = true)
    protected String legalEntityRegistrationNumber;
    @XmlElement(required = true)
    protected String legalEntityRegistrationCountry;
    protected String legalEntityRegistrationProvince;

    /**
     * Gets the value of the legalEntityRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityRegistrationNumber() {
        return legalEntityRegistrationNumber;
    }

    /**
     * Sets the value of the legalEntityRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityRegistrationNumber(String value) {
        this.legalEntityRegistrationNumber = value;
    }

    /**
     * Gets the value of the legalEntityRegistrationCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityRegistrationCountry() {
        return legalEntityRegistrationCountry;
    }

    /**
     * Sets the value of the legalEntityRegistrationCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityRegistrationCountry(String value) {
        this.legalEntityRegistrationCountry = value;
    }

    /**
     * Gets the value of the legalEntityRegistrationProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityRegistrationProvince() {
        return legalEntityRegistrationProvince;
    }

    /**
     * Sets the value of the legalEntityRegistrationProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityRegistrationProvince(String value) {
        this.legalEntityRegistrationProvince = value;
    }

}
