//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v2.common.identitybase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v2.common.identitybase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IndividualNameType }
     * 
     */
    public IndividualNameType createIndividualNameType() {
        return new IndividualNameType();
    }

    /**
     * Create an instance of {@link BeneficiaryLegalEntityIdentityType }
     * 
     */
    public BeneficiaryLegalEntityIdentityType createBeneficiaryLegalEntityIdentityType() {
        return new BeneficiaryLegalEntityIdentityType();
    }

    /**
     * Create an instance of {@link BeneficiaryIdentityType }
     * 
     */
    public BeneficiaryIdentityType createBeneficiaryIdentityType() {
        return new BeneficiaryIdentityType();
    }

    /**
     * Create an instance of {@link UnstructuredIdentityType }
     * 
     */
    public UnstructuredIdentityType createUnstructuredIdentityType() {
        return new UnstructuredIdentityType();
    }

    /**
     * Create an instance of {@link PayerIdentityIDType }
     * 
     */
    public PayerIdentityIDType createPayerIdentityIDType() {
        return new PayerIdentityIDType();
    }

    /**
     * Create an instance of {@link IdentificationListType }
     * 
     */
    public IdentificationListType createIdentificationListType() {
        return new IdentificationListType();
    }

    /**
     * Create an instance of {@link BirthInformationType }
     * 
     */
    public BirthInformationType createBirthInformationType() {
        return new BirthInformationType();
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link PayerAdditionalDataListType }
     * 
     */
    public PayerAdditionalDataListType createPayerAdditionalDataListType() {
        return new PayerAdditionalDataListType();
    }

    /**
     * Create an instance of {@link LegalEntityRegistrationType }
     * 
     */
    public LegalEntityRegistrationType createLegalEntityRegistrationType() {
        return new LegalEntityRegistrationType();
    }

    /**
     * Create an instance of {@link PayerIdentityType }
     * 
     */
    public PayerIdentityType createPayerIdentityType() {
        return new PayerIdentityType();
    }

    /**
     * Create an instance of {@link BeneficiaryIndividualIdentityType }
     * 
     */
    public BeneficiaryIndividualIdentityType createBeneficiaryIndividualIdentityType() {
        return new BeneficiaryIndividualIdentityType();
    }

    /**
     * Create an instance of {@link PayerIndividualIdentityType }
     * 
     */
    public PayerIndividualIdentityType createPayerIndividualIdentityType() {
        return new PayerIndividualIdentityType();
    }

    /**
     * Create an instance of {@link UnstructuredIdentityDataType }
     * 
     */
    public UnstructuredIdentityDataType createUnstructuredIdentityDataType() {
        return new UnstructuredIdentityDataType();
    }

    /**
     * Create an instance of {@link BeneficiaryAdditionalDataType }
     * 
     */
    public BeneficiaryAdditionalDataType createBeneficiaryAdditionalDataType() {
        return new BeneficiaryAdditionalDataType();
    }

    /**
     * Create an instance of {@link PayerAdditionalDataType }
     * 
     */
    public PayerAdditionalDataType createPayerAdditionalDataType() {
        return new PayerAdditionalDataType();
    }

    /**
     * Create an instance of {@link BeneficiaryAdditionalDataListType }
     * 
     */
    public BeneficiaryAdditionalDataListType createBeneficiaryAdditionalDataListType() {
        return new BeneficiaryAdditionalDataListType();
    }

    /**
     * Create an instance of {@link PayerLegalEntityIdentityType }
     * 
     */
    public PayerLegalEntityIdentityType createPayerLegalEntityIdentityType() {
        return new PayerLegalEntityIdentityType();
    }

    /**
     * Create an instance of {@link PayerIdentityResponseType }
     * 
     */
    public PayerIdentityResponseType createPayerIdentityResponseType() {
        return new PayerIdentityResponseType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

}
