//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Represents the payer identity of an individual or
 * 				legal entity.
 * 
 * 				You must specify one of either a payer individual
 * 				identity or payer legal entity identity
 * 				or payer unstructured identity
 * 			
 * 
 * <p>Java class for PayerIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayerIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payerIndividualIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}PayerIndividualIdentityType" minOccurs="0"/>
 *         &lt;element name="payerLegalEntityIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}PayerLegalEntityIdentityType" minOccurs="0"/>
 *         &lt;element name="payerUnstructuredIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}UnstructuredIdentityType" minOccurs="0"/>
 *         &lt;element name="additionalDataList" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}PayerAdditionalDataListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayerIdentityType", propOrder = {
    "payerIndividualIdentity",
    "payerLegalEntityIdentity",
    "payerUnstructuredIdentity",
    "additionalDataList"
})
@XmlSeeAlso({
    PayerIdentityResponseType.class
})
public class PayerIdentityType {

    protected PayerIndividualIdentityType payerIndividualIdentity;
    protected PayerLegalEntityIdentityType payerLegalEntityIdentity;
    protected UnstructuredIdentityType payerUnstructuredIdentity;
    protected PayerAdditionalDataListType additionalDataList;

    /**
     * Gets the value of the payerIndividualIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIndividualIdentityType }
     *     
     */
    public PayerIndividualIdentityType getPayerIndividualIdentity() {
        return payerIndividualIdentity;
    }

    /**
     * Sets the value of the payerIndividualIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIndividualIdentityType }
     *     
     */
    public void setPayerIndividualIdentity(PayerIndividualIdentityType value) {
        this.payerIndividualIdentity = value;
    }

    /**
     * Gets the value of the payerLegalEntityIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link PayerLegalEntityIdentityType }
     *     
     */
    public PayerLegalEntityIdentityType getPayerLegalEntityIdentity() {
        return payerLegalEntityIdentity;
    }

    /**
     * Sets the value of the payerLegalEntityIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerLegalEntityIdentityType }
     *     
     */
    public void setPayerLegalEntityIdentity(PayerLegalEntityIdentityType value) {
        this.payerLegalEntityIdentity = value;
    }

    /**
     * Gets the value of the payerUnstructuredIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link UnstructuredIdentityType }
     *     
     */
    public UnstructuredIdentityType getPayerUnstructuredIdentity() {
        return payerUnstructuredIdentity;
    }

    /**
     * Sets the value of the payerUnstructuredIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnstructuredIdentityType }
     *     
     */
    public void setPayerUnstructuredIdentity(UnstructuredIdentityType value) {
        this.payerUnstructuredIdentity = value;
    }

    /**
     * Gets the value of the additionalDataList property.
     * 
     * @return
     *     possible object is
     *     {@link PayerAdditionalDataListType }
     *     
     */
    public PayerAdditionalDataListType getAdditionalDataList() {
        return additionalDataList;
    }

    /**
     * Sets the value of the additionalDataList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerAdditionalDataListType }
     *     
     */
    public void setAdditionalDataList(PayerAdditionalDataListType value) {
        this.additionalDataList = value;
    }

}
