//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				ComplexType wrapper for the payer identity UID.
 * 			
 * 
 * <p>Java class for PayerIdentityIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayerIdentityIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payerIdentityID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}UIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayerIdentityIDType", propOrder = {
    "payerIdentityID"
})
public class PayerIdentityIDType {

    protected long payerIdentityID;

    /**
     * Gets the value of the payerIdentityID property.
     * 
     */
    public long getPayerIdentityID() {
        return payerIdentityID;
    }

    /**
     * Sets the value of the payerIdentityID property.
     * 
     */
    public void setPayerIdentityID(long value) {
        this.payerIdentityID = value;
    }

}
