//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Represents a set of name value pairs that can be
 * 				supplied as the Identity information.
 * 
 * 				The keys will be validated on the server side against a list of valid
 * 				types that are accepted.
 * 
 * 				Both the key and the value are required.
 * 			
 * 
 * <p>Java class for UnstructuredIdentityDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnstructuredIdentityDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unstructuredIdentityDataKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unstructuredIdentityDataValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnstructuredIdentityDataType", propOrder = {
    "unstructuredIdentityDataKey",
    "unstructuredIdentityDataValue"
})
public class UnstructuredIdentityDataType {

    @XmlElement(required = true)
    protected String unstructuredIdentityDataKey;
    @XmlElement(required = true)
    protected String unstructuredIdentityDataValue;

    /**
     * Gets the value of the unstructuredIdentityDataKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnstructuredIdentityDataKey() {
        return unstructuredIdentityDataKey;
    }

    /**
     * Sets the value of the unstructuredIdentityDataKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnstructuredIdentityDataKey(String value) {
        this.unstructuredIdentityDataKey = value;
    }

    /**
     * Gets the value of the unstructuredIdentityDataValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnstructuredIdentityDataValue() {
        return unstructuredIdentityDataValue;
    }

    /**
     * Sets the value of the unstructuredIdentityDataValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnstructuredIdentityDataValue(String value) {
        this.unstructuredIdentityDataValue = value;
    }

}
