//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v2.common.identitybase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Represents a list of key-value pairs for Identity
 * 			
 * 
 * <p>Java class for UnstructuredIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnstructuredIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unstructuredIdentityData" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/identityBase}UnstructuredIdentityDataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnstructuredIdentityType", propOrder = {
    "unstructuredIdentityData"
})
public class UnstructuredIdentityType {

    @XmlElement(required = true)
    protected List<UnstructuredIdentityDataType> unstructuredIdentityData;

    /**
     * Gets the value of the unstructuredIdentityData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unstructuredIdentityData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnstructuredIdentityData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnstructuredIdentityDataType }
     * 
     * 
     */
    public List<UnstructuredIdentityDataType> getUnstructuredIdentityData() {
        if (unstructuredIdentityData == null) {
            unstructuredIdentityData = new ArrayList<UnstructuredIdentityDataType>();
        }
        return this.unstructuredIdentityData;
    }

}
