//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.purposeOfPaymentBase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Additional fields will be one of two types; 
 * 				free text or list options. 
 * 
 * 				'additionalFieldWithValues' gives a list of
 * 				acceptable responses.
 * 
 * 				'additionalFieldWithValidator' is a free
 * 				text response.  
 * 
 * 			
 * 
 * <p>Java class for additionalFieldsList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="additionalFieldsList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="additionalFieldWithValues" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}additionalFieldWithValues"/>
 *           &lt;element name="additionalFieldWithValidator" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}additionalFieldWithValidator"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "additionalFieldsList", propOrder = {
    "additionalFieldWithValuesOrAdditionalFieldWithValidator"
})
public class AdditionalFieldsList {

    @XmlElements({
        @XmlElement(name = "additionalFieldWithValidator", type = AdditionalFieldWithValidator.class),
        @XmlElement(name = "additionalFieldWithValues", type = AdditionalFieldWithValues.class)
    })
    protected List<Object> additionalFieldWithValuesOrAdditionalFieldWithValidator;

    /**
     * Gets the value of the additionalFieldWithValuesOrAdditionalFieldWithValidator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalFieldWithValuesOrAdditionalFieldWithValidator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalFieldWithValuesOrAdditionalFieldWithValidator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalFieldWithValidator }
     * {@link AdditionalFieldWithValues }
     * 
     * 
     */
    public List<Object> getAdditionalFieldWithValuesOrAdditionalFieldWithValidator() {
        if (additionalFieldWithValuesOrAdditionalFieldWithValidator == null) {
            additionalFieldWithValuesOrAdditionalFieldWithValidator = new ArrayList<Object>();
        }
        return this.additionalFieldWithValuesOrAdditionalFieldWithValidator;
    }

}
