//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.purposeOfPaymentBase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Usage restrictions apply where a specified
 * 				code is only acceptable for a given type of
 * 				payer or beneficiary.
 * 
 * 				This attribute indicates whether the code
 * 				can be used for Individuals and/or Legal Entities,
 * 				for both payer and beneficiary parties.
 * 
 * 				Additional field specifications identify further
 * 				data that is required, given the chosen Purpose
 * 				of Payment.
 * 
 * 			
 * 
 * <p>Java class for purposeOfPaymentUsageRestrictions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purposeOfPaymentUsageRestrictions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="originatorType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}identityRestriction"/>
 *           &lt;element name="beneficiaryType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}identityRestriction"/>
 *           &lt;element name="additionalFieldsList" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}additionalFieldsList" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purposeOfPaymentUsageRestrictions", propOrder = {
    "originatorType",
    "beneficiaryType",
    "additionalFieldsList"
})
public class PurposeOfPaymentUsageRestrictions {

    @XmlElement(required = true)
    protected IdentityRestriction originatorType;
    @XmlElement(required = true)
    protected IdentityRestriction beneficiaryType;
    protected AdditionalFieldsList additionalFieldsList;

    /**
     * Gets the value of the originatorType property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityRestriction }
     *     
     */
    public IdentityRestriction getOriginatorType() {
        return originatorType;
    }

    /**
     * Sets the value of the originatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityRestriction }
     *     
     */
    public void setOriginatorType(IdentityRestriction value) {
        this.originatorType = value;
    }

    /**
     * Gets the value of the beneficiaryType property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityRestriction }
     *     
     */
    public IdentityRestriction getBeneficiaryType() {
        return beneficiaryType;
    }

    /**
     * Sets the value of the beneficiaryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityRestriction }
     *     
     */
    public void setBeneficiaryType(IdentityRestriction value) {
        this.beneficiaryType = value;
    }

    /**
     * Gets the value of the additionalFieldsList property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalFieldsList }
     *     
     */
    public AdditionalFieldsList getAdditionalFieldsList() {
        return additionalFieldsList;
    }

    /**
     * Sets the value of the additionalFieldsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalFieldsList }
     *     
     */
    public void setAdditionalFieldsList(AdditionalFieldsList value) {
        this.additionalFieldsList = value;
    }

}
