//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.purposeOfPaymentBase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				This contains a specific Purpose of Payment
 * 				option, consisting of a code and a human
 * 				readable description.
 * 
 * 			
 * 
 * <p>Java class for purposeOfPaymentCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purposeOfPaymentCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="purposeOfPaymentUsageRestrictions" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}purposeOfPaymentUsageRestrictions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purposeOfPaymentCode", propOrder = {
    "purposeOfPaymentUsageRestrictions"
})
public class PurposeOfPaymentCode {

    protected PurposeOfPaymentUsageRestrictions purposeOfPaymentUsageRestrictions;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "code", required = true)
    protected String code;

    /**
     * Gets the value of the purposeOfPaymentUsageRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link PurposeOfPaymentUsageRestrictions }
     *     
     */
    public PurposeOfPaymentUsageRestrictions getPurposeOfPaymentUsageRestrictions() {
        return purposeOfPaymentUsageRestrictions;
    }

    /**
     * Sets the value of the purposeOfPaymentUsageRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurposeOfPaymentUsageRestrictions }
     *     
     */
    public void setPurposeOfPaymentUsageRestrictions(PurposeOfPaymentUsageRestrictions value) {
        this.purposeOfPaymentUsageRestrictions = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
