//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.searchTransactions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v4.searchTransactions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SearchTransactions_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v4/services/searchTransactions", "searchTransactions");
    private final static QName _SearchTransactionsResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v4/services/searchTransactions", "searchTransactionsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v4.searchTransactions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchTransactionsResponseType }
     * 
     */
    public SearchTransactionsResponseType createSearchTransactionsResponseType() {
        return new SearchTransactionsResponseType();
    }

    /**
     * Create an instance of {@link SearchSortFieldsType }
     * 
     */
    public SearchSortFieldsType createSearchSortFieldsType() {
        return new SearchSortFieldsType();
    }

    /**
     * Create an instance of {@link SearchTransactionsType }
     * 
     */
    public SearchTransactionsType createSearchTransactionsType() {
        return new SearchTransactionsType();
    }

    /**
     * Create an instance of {@link SearchTransactionsCriteriaType }
     * 
     */
    public SearchTransactionsCriteriaType createSearchTransactionsCriteriaType() {
        return new SearchTransactionsCriteriaType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchTransactionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v4/services/searchTransactions", name = "searchTransactions")
    public JAXBElement<SearchTransactionsType> createSearchTransactions(SearchTransactionsType value) {
        return new JAXBElement<SearchTransactionsType>(_SearchTransactions_QNAME, SearchTransactionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchTransactionsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v4/services/searchTransactions", name = "searchTransactionsResponse")
    public JAXBElement<SearchTransactionsResponseType> createSearchTransactionsResponse(SearchTransactionsResponseType value) {
        return new JAXBElement<SearchTransactionsResponseType>(_SearchTransactionsResponse_QNAME, SearchTransactionsResponseType.class, null, value);
    }

}
