//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.searchTransactions;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.earthport.bind.v2.common.core.AbstractSearchCriteriaType;
import com.earthport.bind.v4.common.financialtransaction.FinancialTransactionTypeType;


/**
 * <p>Java class for SearchTransactionsCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchTransactionsCriteriaType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}AbstractSearchCriteriaType">
 *       &lt;sequence>
 *         &lt;element name="periodStartDateTime" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericTimestampType"/>
 *         &lt;element name="periodEndDateTime" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericTimestampType"/>
 *         &lt;element name="currency" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="amountFrom" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericAmountType" minOccurs="0"/>
 *         &lt;element name="amountTo" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}GenericAmountType" minOccurs="0"/>
 *         &lt;element name="epTransactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}PaymentIDType" minOccurs="0"/>
 *         &lt;element name="merchantTransactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantTransactionRefType" minOccurs="0"/>
 *         &lt;element name="transactionType" type="{http://customer.endpoint.earthport.com/api/merchant/v4/components/financialTransactionBase}FinancialTransactionTypeType" minOccurs="0"/>
 *         &lt;element name="transactionStatusCode" type="{http://customer.endpoint.earthport.com/api/merchant/v4/components/financialTransactionBase}StatusCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchTransactionsCriteriaType", propOrder = {
    "periodStartDateTime",
    "periodEndDateTime",
    "currency",
    "amountFrom",
    "amountTo",
    "epTransactionID",
    "merchantTransactionID",
    "transactionType",
    "transactionStatusCode"
})
public class SearchTransactionsCriteriaType
    extends AbstractSearchCriteriaType
{

    @XmlElement(required = true)
    protected XMLGregorianCalendar periodStartDateTime;
    @XmlElement(required = true)
    protected XMLGregorianCalendar periodEndDateTime;
    protected String currency;
    protected BigDecimal amountFrom;
    protected BigDecimal amountTo;
    protected Long epTransactionID;
    protected String merchantTransactionID;
    protected FinancialTransactionTypeType transactionType;
    protected Integer transactionStatusCode;

    /**
     * Gets the value of the periodStartDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodStartDateTime() {
        return periodStartDateTime;
    }

    /**
     * Sets the value of the periodStartDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodStartDateTime(XMLGregorianCalendar value) {
        this.periodStartDateTime = value;
    }

    /**
     * Gets the value of the periodEndDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodEndDateTime() {
        return periodEndDateTime;
    }

    /**
     * Sets the value of the periodEndDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodEndDateTime(XMLGregorianCalendar value) {
        this.periodEndDateTime = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the amountFrom property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountFrom() {
        return amountFrom;
    }

    /**
     * Sets the value of the amountFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountFrom(BigDecimal value) {
        this.amountFrom = value;
    }

    /**
     * Gets the value of the amountTo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountTo() {
        return amountTo;
    }

    /**
     * Sets the value of the amountTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountTo(BigDecimal value) {
        this.amountTo = value;
    }

    /**
     * Gets the value of the epTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEpTransactionID() {
        return epTransactionID;
    }

    /**
     * Sets the value of the epTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEpTransactionID(Long value) {
        this.epTransactionID = value;
    }

    /**
     * Gets the value of the merchantTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTransactionID() {
        return merchantTransactionID;
    }

    /**
     * Sets the value of the merchantTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTransactionID(String value) {
        this.merchantTransactionID = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialTransactionTypeType }
     *     
     */
    public FinancialTransactionTypeType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialTransactionTypeType }
     *     
     */
    public void setTransactionType(FinancialTransactionTypeType value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the transactionStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransactionStatusCode() {
        return transactionStatusCode;
    }

    /**
     * Sets the value of the transactionStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransactionStatusCode(Integer value) {
        this.transactionStatusCode = value;
    }

}
