//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.searchTransactions;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.core.PaginationType;


/**
 * <p>Java class for SearchTransactionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchTransactionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="managedMerchantIdentity" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MerchantIdentityType" minOccurs="0"/>
 *         &lt;element name="searchTransactionsCriteria" type="{http://customer.endpoint.earthport.com/api/merchant/v4/services/searchTransactions}SearchTransactionsCriteriaType"/>
 *         &lt;element name="pagination" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}PaginationType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchTransactionsType", propOrder = {
    "managedMerchantIdentity",
    "searchTransactionsCriteria",
    "pagination"
})
public class SearchTransactionsType {

    protected String managedMerchantIdentity;
    @XmlElement(required = true)
    protected SearchTransactionsCriteriaType searchTransactionsCriteria;
    @XmlElement(required = true)
    protected PaginationType pagination;
    @XmlAttribute(name = "version", required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the managedMerchantIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagedMerchantIdentity() {
        return managedMerchantIdentity;
    }

    /**
     * Sets the value of the managedMerchantIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagedMerchantIdentity(String value) {
        this.managedMerchantIdentity = value;
    }

    /**
     * Gets the value of the searchTransactionsCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link SearchTransactionsCriteriaType }
     *     
     */
    public SearchTransactionsCriteriaType getSearchTransactionsCriteria() {
        return searchTransactionsCriteria;
    }

    /**
     * Sets the value of the searchTransactionsCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchTransactionsCriteriaType }
     *     
     */
    public void setSearchTransactionsCriteria(SearchTransactionsCriteriaType value) {
        this.searchTransactionsCriteria = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link PaginationType }
     *     
     */
    public PaginationType getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaginationType }
     *     
     */
    public void setPagination(PaginationType value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
