//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v3.getFXQuote;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v1.common.payoutbase.ServiceLevelType;
import com.earthport.bind.v2.common.core.MonetaryValueType;
import com.earthport.bind.v3.common.bankbase.UsersBankIDType;


/**
 * <p>Java class for GetFXQuoteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetFXQuoteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sellAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="buyCurrency" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="buyAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="sellCurrency" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CurrencyCodeType" minOccurs="0"/>
 *         &lt;element name="serviceLevel" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}ServiceLevelType" minOccurs="0"/>
 *         &lt;element name="usersBankID" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}UsersBankIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetFXQuoteType", propOrder = {
    "sellAmount",
    "buyCurrency",
    "buyAmount",
    "sellCurrency",
    "serviceLevel",
    "usersBankID"
})
public class GetFXQuoteType {

    protected MonetaryValueType sellAmount;
    protected String buyCurrency;
    protected MonetaryValueType buyAmount;
    protected String sellCurrency;
    @XmlElement(defaultValue = "standard")
    protected ServiceLevelType serviceLevel;
    protected UsersBankIDType usersBankID;
    @XmlAttribute(name = "version", required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the sellAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getSellAmount() {
        return sellAmount;
    }

    /**
     * Sets the value of the sellAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setSellAmount(MonetaryValueType value) {
        this.sellAmount = value;
    }

    /**
     * Gets the value of the buyCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyCurrency() {
        return buyCurrency;
    }

    /**
     * Sets the value of the buyCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyCurrency(String value) {
        this.buyCurrency = value;
    }

    /**
     * Gets the value of the buyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getBuyAmount() {
        return buyAmount;
    }

    /**
     * Sets the value of the buyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setBuyAmount(MonetaryValueType value) {
        this.buyAmount = value;
    }

    /**
     * Gets the value of the sellCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellCurrency() {
        return sellCurrency;
    }

    /**
     * Sets the value of the sellCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellCurrency(String value) {
        this.sellCurrency = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceLevelType }
     *     
     */
    public ServiceLevelType getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceLevelType }
     *     
     */
    public void setServiceLevel(ServiceLevelType value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the usersBankID property.
     * 
     * @return
     *     possible object is
     *     {@link UsersBankIDType }
     *     
     */
    public UsersBankIDType getUsersBankID() {
        return usersBankID;
    }

    /**
     * Sets the value of the usersBankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersBankIDType }
     *     
     */
    public void setUsersBankID(UsersBankIDType value) {
        this.usersBankID = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
