//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.getPayoutRequiredData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v1.common.identityFieldsBase.BeneficiaryIdentityGroupsListType;
import com.earthport.bind.v1.common.purposeOfPaymentBase.PurposeOfPaymentFieldGroupsList;
import com.earthport.bind.v3.common.bankbase.BeneficiaryBankAccountGroupsListType;


/**
 * <p>Java class for GetPayoutRequiredDataResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetPayoutRequiredDataResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="getPayoutRequiredDataForBank" type="{http://customer.endpoint.earthport.com/api/merchant/v1/services/getPayoutRequiredData}getPayoutRequiredDataForBank"/>
 *           &lt;sequence>
 *             &lt;element name="getPayoutRequiredDataForCountryCurrency" type="{http://customer.endpoint.earthport.com/api/merchant/v1/services/getPayoutRequiredData}getPayoutRequiredDataForCountryCurrency"/>
 *             &lt;element name="beneficiaryIdentityFieldGroupsList" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/identityFieldsBase}BeneficiaryIdentityGroupsListType"/>
 *             &lt;element name="beneficiaryBankAccountFieldGroupsList" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountGroupsListType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="purposeOfPaymentFieldGroupsList" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/purposeOfPaymentBase}purposeOfPaymentFieldGroupsList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetPayoutRequiredDataResponseType", propOrder = {
    "getPayoutRequiredDataForBank",
    "getPayoutRequiredDataForCountryCurrency",
    "beneficiaryIdentityFieldGroupsList",
    "beneficiaryBankAccountFieldGroupsList",
    "purposeOfPaymentFieldGroupsList"
})
public class GetPayoutRequiredDataResponseType {

    protected GetPayoutRequiredDataForBank getPayoutRequiredDataForBank;
    protected GetPayoutRequiredDataForCountryCurrency getPayoutRequiredDataForCountryCurrency;
    protected BeneficiaryIdentityGroupsListType beneficiaryIdentityFieldGroupsList;
    protected BeneficiaryBankAccountGroupsListType beneficiaryBankAccountFieldGroupsList;
    protected PurposeOfPaymentFieldGroupsList purposeOfPaymentFieldGroupsList;

    /**
     * Gets the value of the getPayoutRequiredDataForBank property.
     * 
     * @return
     *     possible object is
     *     {@link GetPayoutRequiredDataForBank }
     *     
     */
    public GetPayoutRequiredDataForBank getGetPayoutRequiredDataForBank() {
        return getPayoutRequiredDataForBank;
    }

    /**
     * Sets the value of the getPayoutRequiredDataForBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPayoutRequiredDataForBank }
     *     
     */
    public void setGetPayoutRequiredDataForBank(GetPayoutRequiredDataForBank value) {
        this.getPayoutRequiredDataForBank = value;
    }

    /**
     * Gets the value of the getPayoutRequiredDataForCountryCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link GetPayoutRequiredDataForCountryCurrency }
     *     
     */
    public GetPayoutRequiredDataForCountryCurrency getGetPayoutRequiredDataForCountryCurrency() {
        return getPayoutRequiredDataForCountryCurrency;
    }

    /**
     * Sets the value of the getPayoutRequiredDataForCountryCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPayoutRequiredDataForCountryCurrency }
     *     
     */
    public void setGetPayoutRequiredDataForCountryCurrency(GetPayoutRequiredDataForCountryCurrency value) {
        this.getPayoutRequiredDataForCountryCurrency = value;
    }

    /**
     * Gets the value of the beneficiaryIdentityFieldGroupsList property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryIdentityGroupsListType }
     *     
     */
    public BeneficiaryIdentityGroupsListType getBeneficiaryIdentityFieldGroupsList() {
        return beneficiaryIdentityFieldGroupsList;
    }

    /**
     * Sets the value of the beneficiaryIdentityFieldGroupsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryIdentityGroupsListType }
     *     
     */
    public void setBeneficiaryIdentityFieldGroupsList(BeneficiaryIdentityGroupsListType value) {
        this.beneficiaryIdentityFieldGroupsList = value;
    }

    /**
     * Gets the value of the beneficiaryBankAccountFieldGroupsList property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryBankAccountGroupsListType }
     *     
     */
    public BeneficiaryBankAccountGroupsListType getBeneficiaryBankAccountFieldGroupsList() {
        return beneficiaryBankAccountFieldGroupsList;
    }

    /**
     * Sets the value of the beneficiaryBankAccountFieldGroupsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryBankAccountGroupsListType }
     *     
     */
    public void setBeneficiaryBankAccountFieldGroupsList(BeneficiaryBankAccountGroupsListType value) {
        this.beneficiaryBankAccountFieldGroupsList = value;
    }

    /**
     * Gets the value of the purposeOfPaymentFieldGroupsList property.
     * 
     * @return
     *     possible object is
     *     {@link PurposeOfPaymentFieldGroupsList }
     *     
     */
    public PurposeOfPaymentFieldGroupsList getPurposeOfPaymentFieldGroupsList() {
        return purposeOfPaymentFieldGroupsList;
    }

    /**
     * Sets the value of the purposeOfPaymentFieldGroupsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurposeOfPaymentFieldGroupsList }
     *     
     */
    public void setPurposeOfPaymentFieldGroupsList(PurposeOfPaymentFieldGroupsList value) {
        this.purposeOfPaymentFieldGroupsList = value;
    }

}
