//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.getPayoutRequiredData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v1.common.payoutbase.ServiceLevelType;


/**
 * <p>Java class for getPayoutRequiredDataForCountryCurrency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getPayoutRequiredDataForCountryCurrency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="countryCode" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CountryCodeType"/>
 *         &lt;element name="currencyCode" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}CurrencyCodeType"/>
 *         &lt;element name="beneficiaryIdentityEntityType" type="{http://customer.endpoint.earthport.com/api/merchant/v1/services/getPayoutRequiredData}IdentityEntityType" minOccurs="0"/>
 *         &lt;element name="locale" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}LocaleType" minOccurs="0"/>
 *         &lt;element name="serviceLevel" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/payoutBase}ServiceLevelType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPayoutRequiredDataForCountryCurrency", propOrder = {
    "countryCode",
    "currencyCode",
    "beneficiaryIdentityEntityType",
    "locale",
    "serviceLevel"
})
public class GetPayoutRequiredDataForCountryCurrency {

    @XmlElement(required = true)
    protected String countryCode;
    @XmlElement(required = true)
    protected String currencyCode;
    protected IdentityEntityType beneficiaryIdentityEntityType;
    protected String locale;
    protected ServiceLevelType serviceLevel;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the beneficiaryIdentityEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityEntityType }
     *     
     */
    public IdentityEntityType getBeneficiaryIdentityEntityType() {
        return beneficiaryIdentityEntityType;
    }

    /**
     * Sets the value of the beneficiaryIdentityEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityEntityType }
     *     
     */
    public void setBeneficiaryIdentityEntityType(IdentityEntityType value) {
        this.beneficiaryIdentityEntityType = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceLevelType }
     *     
     */
    public ServiceLevelType getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceLevelType }
     *     
     */
    public void setServiceLevel(ServiceLevelType value) {
        this.serviceLevel = value;
    }

}
