//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.listBeneficiaryBankAccounts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.core.PaginationResultType;
import com.earthport.bind.v2.common.core.UserIDType;
import com.earthport.bind.v3.common.bankbase.BeneficiaryBankAccountSummaryType;


/**
 * <p>Java class for ListBeneficiaryBankAccountsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListBeneficiaryBankAccountsResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beneficiaryBankAccountSummary" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}BeneficiaryBankAccountSummaryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="userID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}UserIDType"/>
 *         &lt;element name="paginationResult" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}PaginationResultType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListBeneficiaryBankAccountsResponseType", propOrder = {
    "beneficiaryBankAccountSummary",
    "userID",
    "paginationResult"
})
public class ListBeneficiaryBankAccountsResponseType {

    protected List<BeneficiaryBankAccountSummaryType> beneficiaryBankAccountSummary;
    @XmlElement(required = true)
    protected UserIDType userID;
    @XmlElement(required = true)
    protected PaginationResultType paginationResult;

    /**
     * Gets the value of the beneficiaryBankAccountSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beneficiaryBankAccountSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeneficiaryBankAccountSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeneficiaryBankAccountSummaryType }
     * 
     * 
     */
    public List<BeneficiaryBankAccountSummaryType> getBeneficiaryBankAccountSummary() {
        if (beneficiaryBankAccountSummary == null) {
            beneficiaryBankAccountSummary = new ArrayList<BeneficiaryBankAccountSummaryType>();
        }
        return this.beneficiaryBankAccountSummary;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link UserIDType }
     *     
     */
    public UserIDType getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIDType }
     *     
     */
    public void setUserID(UserIDType value) {
        this.userID = value;
    }

    /**
     * Gets the value of the paginationResult property.
     * 
     * @return
     *     possible object is
     *     {@link PaginationResultType }
     *     
     */
    public PaginationResultType getPaginationResult() {
        return paginationResult;
    }

    /**
     * Sets the value of the paginationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaginationResultType }
     *     
     */
    public void setPaginationResult(PaginationResultType value) {
        this.paginationResult = value;
    }

}
