//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v4.listBeneficiaryBankAccounts;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v4.listBeneficiaryBankAccounts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListBeneficiaryBankAccountsResponse_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v4/services/listBeneficiaryBankAccounts", "listBeneficiaryBankAccountsResponse");
    private final static QName _ListBeneficiaryBankAccounts_QNAME = new QName("http://customer.endpoint.earthport.com/api/merchant/v4/services/listBeneficiaryBankAccounts", "listBeneficiaryBankAccounts");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v4.listBeneficiaryBankAccounts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListBeneficiaryBankAccountsType }
     * 
     */
    public ListBeneficiaryBankAccountsType createListBeneficiaryBankAccountsType() {
        return new ListBeneficiaryBankAccountsType();
    }

    /**
     * Create an instance of {@link ListBeneficiaryBankAccountsResponseType }
     * 
     */
    public ListBeneficiaryBankAccountsResponseType createListBeneficiaryBankAccountsResponseType() {
        return new ListBeneficiaryBankAccountsResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListBeneficiaryBankAccountsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v4/services/listBeneficiaryBankAccounts", name = "listBeneficiaryBankAccountsResponse")
    public JAXBElement<ListBeneficiaryBankAccountsResponseType> createListBeneficiaryBankAccountsResponse(ListBeneficiaryBankAccountsResponseType value) {
        return new JAXBElement<ListBeneficiaryBankAccountsResponseType>(_ListBeneficiaryBankAccountsResponse_QNAME, ListBeneficiaryBankAccountsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListBeneficiaryBankAccountsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://customer.endpoint.earthport.com/api/merchant/v4/services/listBeneficiaryBankAccounts", name = "listBeneficiaryBankAccounts")
    public JAXBElement<ListBeneficiaryBankAccountsType> createListBeneficiaryBankAccounts(ListBeneficiaryBankAccountsType value) {
        return new JAXBElement<ListBeneficiaryBankAccountsType>(_ListBeneficiaryBankAccounts_QNAME, ListBeneficiaryBankAccountsType.class, null, value);
    }

}
