//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.notificationbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.core.MonetaryValueType;


/**
 * 
 * 				A financial transaction representing a payout from an account held in the EPS system.
 * 			
 * 
 * <p>Java class for DepositNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DepositNotificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v1/components/notificationBase}NotificationType">
 *       &lt;sequence>
 *         &lt;element name="depositAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *         &lt;element name="depositedAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepositNotificationType", propOrder = {
    "depositAmount",
    "depositedAmount"
})
public class DepositNotificationType
    extends NotificationType
{

    protected MonetaryValueType depositAmount;
    protected MonetaryValueType depositedAmount;

    /**
     * Gets the value of the depositAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getDepositAmount() {
        return depositAmount;
    }

    /**
     * Sets the value of the depositAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setDepositAmount(MonetaryValueType value) {
        this.depositAmount = value;
    }

    /**
     * Gets the value of the depositedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getDepositedAmount() {
        return depositedAmount;
    }

    /**
     * Sets the value of the depositedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setDepositedAmount(MonetaryValueType value) {
        this.depositedAmount = value;
    }

}
