//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.notificationbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationAcknowledgementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationAcknowledgementType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v1/components/notificationBase}AcknowledgementType">
 *       &lt;sequence>
 *         &lt;element name="epTransactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}PaymentIDType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationAcknowledgementType", propOrder = {
    "epTransactionID"
})
public class NotificationAcknowledgementType
    extends AcknowledgementType
{

    protected long epTransactionID;

    /**
     * Gets the value of the epTransactionID property.
     * 
     */
    public long getEpTransactionID() {
        return epTransactionID;
    }

    /**
     * Sets the value of the epTransactionID property.
     * 
     */
    public void setEpTransactionID(long value) {
        this.epTransactionID = value;
    }

}
