//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.notificationbase;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.earthport.bind.v1.common.notificationbase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.earthport.bind.v1.common.notificationbase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcknowledgeBatchNotificationsType }
     * 
     */
    public AcknowledgeBatchNotificationsType createAcknowledgeBatchNotificationsType() {
        return new AcknowledgeBatchNotificationsType();
    }

    /**
     * Create an instance of {@link WalletPaymentStatusNotificationType }
     * 
     */
    public WalletPaymentStatusNotificationType createWalletPaymentStatusNotificationType() {
        return new WalletPaymentStatusNotificationType();
    }

    /**
     * Create an instance of {@link NotificationAcknowledgementType }
     * 
     */
    public NotificationAcknowledgementType createNotificationAcknowledgementType() {
        return new NotificationAcknowledgementType();
    }

    /**
     * Create an instance of {@link PayoutTransactionIDType }
     * 
     */
    public PayoutTransactionIDType createPayoutTransactionIDType() {
        return new PayoutTransactionIDType();
    }

    /**
     * Create an instance of {@link RejectNotificationType }
     * 
     */
    public RejectNotificationType createRejectNotificationType() {
        return new RejectNotificationType();
    }

    /**
     * Create an instance of {@link WalletPaymentFailureReasonListType }
     * 
     */
    public WalletPaymentFailureReasonListType createWalletPaymentFailureReasonListType() {
        return new WalletPaymentFailureReasonListType();
    }

    /**
     * Create an instance of {@link WalletPaymentFailureReasonType }
     * 
     */
    public WalletPaymentFailureReasonType createWalletPaymentFailureReasonType() {
        return new WalletPaymentFailureReasonType();
    }

    /**
     * Create an instance of {@link NotificationListType }
     * 
     */
    public NotificationListType createNotificationListType() {
        return new NotificationListType();
    }

    /**
     * Create an instance of {@link DepositNotificationType }
     * 
     */
    public DepositNotificationType createDepositNotificationType() {
        return new DepositNotificationType();
    }

    /**
     * Create an instance of {@link ReturnNotificationType }
     * 
     */
    public ReturnNotificationType createReturnNotificationType() {
        return new ReturnNotificationType();
    }

}
