//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.notificationbase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.earthport.bind.v2.common.core.MonetaryValueType;


/**
 * 
 * 				A financial transaction representing a payout from an account held in the EPS system.
 * 			
 * 
 * <p>Java class for ReturnNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnNotificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v1/components/notificationBase}NotificationType">
 *       &lt;sequence>
 *         &lt;element name="refundedAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *         &lt;element name="payoutAmount" type="{http://customer.endpoint.earthport.com/api/merchant/v2/components/core}MonetaryValueType"/>
 *         &lt;element name="payoutTransactionID" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/notificationBase}PayoutTransactionIDType"/>
 *         &lt;element name="epBankID" type="{http://customer.endpoint.earthport.com/api/merchant/v3/components/bankBase}EPBankIDType"/>
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnNotificationType", propOrder = {
    "refundedAmount",
    "payoutAmount",
    "payoutTransactionID",
    "epBankID",
    "reason",
    "reasonID"
})
public class ReturnNotificationType
    extends NotificationType
{

    @XmlElement(required = true)
    protected MonetaryValueType refundedAmount;
    @XmlElement(required = true)
    protected MonetaryValueType payoutAmount;
    @XmlElement(required = true)
    protected PayoutTransactionIDType payoutTransactionID;
    protected long epBankID;
    @XmlElement(required = true)
    protected String reason;
    protected int reasonID;

    /**
     * Gets the value of the refundedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getRefundedAmount() {
        return refundedAmount;
    }

    /**
     * Sets the value of the refundedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setRefundedAmount(MonetaryValueType value) {
        this.refundedAmount = value;
    }

    /**
     * Gets the value of the payoutAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValueType }
     *     
     */
    public MonetaryValueType getPayoutAmount() {
        return payoutAmount;
    }

    /**
     * Sets the value of the payoutAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValueType }
     *     
     */
    public void setPayoutAmount(MonetaryValueType value) {
        this.payoutAmount = value;
    }

    /**
     * Gets the value of the payoutTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link PayoutTransactionIDType }
     *     
     */
    public PayoutTransactionIDType getPayoutTransactionID() {
        return payoutTransactionID;
    }

    /**
     * Sets the value of the payoutTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayoutTransactionIDType }
     *     
     */
    public void setPayoutTransactionID(PayoutTransactionIDType value) {
        this.payoutTransactionID = value;
    }

    /**
     * Gets the value of the epBankID property.
     * 
     */
    public long getEpBankID() {
        return epBankID;
    }

    /**
     * Sets the value of the epBankID property.
     * 
     */
    public void setEpBankID(long value) {
        this.epBankID = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the reasonID property.
     * 
     */
    public int getReasonID() {
        return reasonID;
    }

    /**
     * Sets the value of the reasonID property.
     * 
     */
    public void setReasonID(int value) {
        this.reasonID = value;
    }

}
