//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:56:52 AM IST 
//


package com.earthport.bind.v1.common.notificationbase;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			A notification sent to inform a merchant of a state change of wallet payment
 * 			For instance a notification that the payment has been sent or rejected.
 * 		
 * 
 * <p>Java class for WalletPaymentStatusNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WalletPaymentStatusNotificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://customer.endpoint.earthport.com/api/merchant/v1/components/notificationBase}NotificationType">
 *       &lt;sequence>
 *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="statusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="failureReasons" type="{http://customer.endpoint.earthport.com/api/merchant/v1/components/notificationBase}WalletPaymentFailureReasonListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WalletPaymentStatusNotificationType", propOrder = {
    "statusCode",
    "statusDescription",
    "failureReasons"
})
public class WalletPaymentStatusNotificationType
    extends NotificationType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger statusCode;
    @XmlElement(required = true)
    protected String statusDescription;
    protected WalletPaymentFailureReasonListType failureReasons;

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusCode(BigInteger value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDescription() {
        return statusDescription;
    }

    /**
     * Sets the value of the statusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDescription(String value) {
        this.statusDescription = value;
    }

    /**
     * Gets the value of the failureReasons property.
     * 
     * @return
     *     possible object is
     *     {@link WalletPaymentFailureReasonListType }
     *     
     */
    public WalletPaymentFailureReasonListType getFailureReasons() {
        return failureReasons;
    }

    /**
     * Sets the value of the failureReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletPaymentFailureReasonListType }
     *     
     */
    public void setFailureReasons(WalletPaymentFailureReasonListType value) {
        this.failureReasons = value;
    }

}
